### ISSUE TITLE
Ollama does not recognize models that were copied

### ISSUE THREAD

**Issue by zaredh** [ollama/ollama#10110]
### What is the issue?

I'm trying to copy the contents of the models on my host machine into a docker container. This is how I'm constructing the docker-compose.yml:

```
ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: ollama
    restart: always
    ports:
      - "8006:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ${MODELS_DIR}:/usr/share/ollama/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

This is the contents of the Dockerfile:
```
FROM ollama/ollama

EXPOSE 11434

CMD []
```

Yes, I'm aware that I don't need a Dockerfile for this, I've obfuscated some things from it.

MODELS_DIR  is set in the .env to /usr/share/ollama/.ollama. When I exec into the container after startup, the contents of my host machine are exactly replicated in /usr/share/ollama/.ollama. 

`ollama list` returns an empty list. Restarting the container does not resolve the issue either. 

There is no Modelfile by default stored under manifests/registry.ollama.ai/library/

For example with llama3.1, the library is library/llama3.1/latest. 

### Relevant log output

```shell

```

### OS

Linux

### GPU

Nvidia

### Ollama version

0.6.2
