### ISSUE TITLE
Zeroconf (mDNS/Bonjour) Support for LAN Discovery

### ISSUE THREAD

**Issue by danemadsen** [ollama/ollama#10283]
It would be helpful if Ollama instances could advertise themselves over Zeroconf (mDNS) on the local network, enabling seamless discovery by other devices and apps (e.g. mobile clients, browser frontends, embedded devices).

This would allow clients to automatically discover Ollama instances without manual IP or port configuration, which is especially useful in LAN setups for distributed AI inference or collaborative environments.

Proposed Service Format:
```yaml
Service Type: _ollama._tcp.local.
Service Name: <Hostname or InstanceName>
Port: 11434
TXT Records:
  - model=llama3
  - status=ready
  - version=0.1.25
```
