### ISSUE TITLE
Log request/response payload content

### ISSUE THREAD

**Issue by phucly01** [ollama/ollama#10975]
I tried to troubleshoot a tool calling problem and wanted to see the payload contents of the http request.  I have turned on DEBUG but it doesn't really help. The log only show http code and uri. 

It would be helpful if there is a way to turn on the details log where http requests and responses can be printed in the log along with payload contents.

**Comment by rick-github** [comment]
Setting `OLLAMA_DEBUG=2` will show the prompt as well.

Logging HTTP requests and responses is usually done with an external tool.  For example, mitmdump:
```yaml
services:
  ollama-backend:
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    volumes:
      - ${OLLAMA_MODELS-./ollama}:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=${OLLAMA_KEEP_ALIVE--1}
      - OLLAMA_DEBUG=${OLLAMA_DEBUG-2}

  ollama-mitmproxy:
    image: mitmproxy/mitmproxy
    command: [ "/usr/local/bin/mitmdump", "--flow-detail", "4", "--mode", "reverse:http://ollama-backend:11434" ]
    ports:
      - 11434:8080
```
I use docker here as a environment management tool but this can be run from the command line as well.  The downside of this is that mitmproxy buffers the output so the streaming effect is lost.

In non-Windows environments `nc` can be used as a mitm proxy to record traffic:
```sh
# start ollama listening on a different port
OLLAMA_HOST=localhost:11435 ollama serve
# run a process on the original port that fowards traffic to ollama and records in a file
! [ -p pipe ] && mknod pipe p
nc -ln -p 11434 < pipe | tee -a traffic-in.log | nc localhost 11435 | tee -a traffic-out.log > pipe
```
Other alternatives are `tcpdump` and `tcpflow` which intercept the traffic without having to set up a proxy.  The output of those requires some post-processing.
