### ISSUE TITLE
how to set OLLAMA_NUM_PARALLEL in Ollama docker container ?

### ISSUE THREAD

**Issue by doyoungim999** [ollama/ollama#11082]
### What is the issue?

I want to limit CPU usage in ollama container. 
How to add "OLLAMA_NUM_PARALLEL=4" in ollama docker container? 

### Relevant log output

```shell

```

**Comment by rick-github** [comment]
`OLLAMA_NUM_PARALLEL` doesn't really have anything to do with limiting CPU usage, but this is how to set it in docker compose:

```yaml
services:
  ollama:
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    environment:
      - OLLAMA_NUM_PARALLEL=4
    ports:
      - 11434:11434
```
Or via docker run:
```
docker run --rm --env OLLAMA_NUM_PARALLEL=4 -p 11434:11434 -d --name ollama ollama/ollama
```
