### ISSUE TITLE
multiple models at once

### ISSUE THREAD

**Issue by iplayfast** [ollama/ollama#1307]
I've found that some models are good a coding, while others are good for speaking  and others are good for logic. 
Some of these models are actually quite small, and could possibly fit two or three into the gpu at the same time, (given a high end gpu).

As an enhancement, it would be good to keep models in memory if possible. That way if I have several processes going, that expect different models there is no delay while swapping them out. 

I suggest /set priority=0-9
where a priority 0 (the highest)  is always stay in memory unless it absolutely cannot be (ie another model needs the space)
priority 1-9 is stay in memory unless another model has a higher priority (ie another model is lower).

**Comment by igorschlum** [comment]
I purchased a 192 GB RAM MacStation to run Ollama with various LLMs. I concur that it would be advantageous to keep them resident in memory if possible.

**Comment by gatepoet** [comment]
My current workaround is to start several ollama servers, then using litellm as a proxy, configuring secific models to specific ollama instances. I also modified `routes.go` line 60 to prevent the model from getting killed too often. 
```go
var defaultSessionDuration = 30 * time.Minute
```

It's a bit messy, but it sort of works for now. 

But it would be really nice to have ollama manage it.

**Comment by easp** [comment]
@igorschlum The model data should remain in RAM the file cache. So switching between models will be relatively fast as long as you have enough RAM.

I just checked with a 7.7GB model on my 32GB machine.  First load took ~10s. I restarted the Ollama app (to kill the ollama-runner) and then did `ollama run` again and got the interactive prompt in ~1s.

**Comment by ishaan-jaff** [comment]
@gatepoet we provide a config to start the proxy, if you want to start multiple ollama models too 
https://docs.litellm.ai/docs/simple_proxy#proxy-configs 

```yaml
model_list:
  - model_name: zephyr-alpha # the 1st model is the default on the proxy
    litellm_params: 
      model: huggingface/HuggingFaceH4/zephyr-7b-alpha
      api_base: http://0.0.0.0:8001
  - model_name: gpt-4
    litellm_params:
      model: ollama/code-llama
      api_base: 
  - model_name: claude-2
    litellm_params:
      model: ollama/llama2
      api_base:    
```
