### ISSUE TITLE
Provide instructions for running Ollama as a service in a GitLab CI/CD job

### ISSUE THREAD

**Issue by Bengt** [ollama/ollama#1869]
I have an GitLab CI/CD job that runs my tests like this:

```yaml
run-pytest-python3.11:
    needs:
        -   build-pytest-python3.11
    coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
    image:
        # yamllint disable-line rule:line-length
        name: registry.gitlab.com/openknowledge-gmbh/projects/ml-platform/1-llm-chatbot:pytest-python3.11-latest
        entrypoint: [""]
    script:
        -   cd /1-llm-chatbot
        -   PYTHONPATH=. venv/bin/python -m pytest --cov=llm_chatbot
```

My test suite includes tests of the code that uses the Ollama server to answer the test requests. How do I run `ollama serve` as a [GitLab service](https://docs.gitlab.com/ee/ci/services/)?

**Comment by aliirz** [comment]
Have you considered running Ollama as a docker container and then exposing it as GitLab service?

**Comment by mxyng** [comment]
+1 to running as a GitLab service.

Here's an (unvetted) example:

```yaml
my-job:
  services:
    - name: ollama/ollama:0.1.19
      alias: ollama
  script:
    - nc -vz ollama 11434
```

**Comment by Bengt** [comment]
When I try that, I get the following error:

```
Error: could not connect to ollama server, run 'ollama serve' to start it
```

**Comment by Bengt** [comment]
Setting `OLLAMA_HOST`did not help, either.

**Comment by Bengt** [comment]
Activating the service logging like so:

https://docs.gitlab.com/ee/ci/services/#capturing-service-container-logs

```
variables:
  CI_DEBUG_SERVICES: "true"
```

Gives this:

```

Waiting for services to be up and running (timeout 30 seconds)...
[service:ollama__ollama-ollama-ollama-ollama] 2024-01-10T19:38:24.835151997Z Couldn't find '/root/.ollama/id_ed25519'. Generating new private key.
[service:ollama__ollama-ollama-ollama-ollama] 2024-01-10T19:38:24.837068506Z Your new public key is: 
[service:ollama__ollama-ollama-ollama-ollama] 2024-01-10T19:38:24.837079866Z 
[service:ollama__ollama-ollama-ollama-ollama] 2024-01-10T19:38:24.837084625Z ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOzRULmG6k0cYtK68EBuTNrFNw0CvVI/sVR8XqaHSj5F
[service:ollama__ollama-ollama-ollama-ollama] 2024-01-10T19:38:24.837088825Z 
[service:ollama__ollama-ollama-ollama-ollama] 2024-01-10T19:38:24.838342722Z 2024/01/10 19:38:24 images.go:808: total blobs: 0
[service:ollama__ollama-ollama-ollama-ollama] 2024-01-10T19:38:24.838445250Z 2024/01/10 19:38:24 images.go:815: total unused blobs removed: 0
[service:ollama__ollama-ollama-ollama-ollama] 2024-01-10T19:38:24.838710697Z 2024/01/10 19:38:24 routes.go:930: Listening on [::]:[11](https://gitlab.com/openknowledge-gmbh/projects/ml-platform/1-llm-chatbot/-/jobs/5904376120#L11)434 (version 0.1.19)
[service:ollama__ollama-ollama-ollama-ollama] 2024-01-10T19:38:25.495087885Z 2024/01/10 19:38:25 shim_ext_server.go:[14](https://gitlab.com/openknowledge-gmbh/projects/ml-platform/1-llm-chatbot/-/jobs/5904376120#L14)2: Dynamic LLM variants [cuda]
[service:ollama__ollama-ollama-ollama-ollama] 2024-01-10T19:38:25.495117114Z 2024/01/10 19:38:25 gpu.go:35: Detecting GPU type
[service:ollama__ollama-ollama-ollama-ollama] 2024-01-10T19:38:25.495682538Z 2024/01/10 19:38:25 gpu.go:40: CUDA not detected: Unable to load libnvidia-ml.so library to query for Nvidia GPUs: /usr/lib/wsl/lib/libnvidia-ml.so.1: cannot open shared object file: No such file or directory
[service:ollama__ollama-ollama-ollama-ollama] 2024-01-10T19:38:25.495820096Z 2024/01/10 19:38:25 gpu.go:46: ROCm not detected: Unable to load librocm_smi64.so library to query for Radeon GPUs: /opt/rocm/lib/librocm_smi64.so: cannot open shared object file: No such file or directory
[service:ollama__ollama-ollama-ollama-ollama] 2024-01-10T19:38:25.495838[16](https://gitlab.com/openknowledge-gmbh/projects/ml-platform/1-llm-chatbot/-/jobs/5904376120#L16)6Z 2024/01/10 [19](https://gitlab.com/openknowledge-gmbh/projects/ml-platform/1-llm-chatbot/-/jobs/5904376120#L19):38:25 routes.go:953: no GPU detected
```

**Comment by Bengt** [comment]
Do I maybe need to configure the web origin hosts?

https://github.com/jmorganca/ollama/blob/main/docs/faq.md#how-can-i-allow-additional-web-origins-to-access-ollama

**Comment by mxyng** [comment]
Logs indicate the service is up and running and serving 0.0.0.0:

```
[service:ollama__ollama-ollama-ollama-ollama] 2024-01-10T19:38:24.838710697Z 2024/01/10 19:38:24 routes.go:930: Listening on [::]:[11](https://gitlab.com/openknowledge-gmbh/projects/ml-platform/1-llm-chatbot/-/jobs/5904376120#L11)434 (version 0.1.19)
```

Keep in mind the address GitLab exposes is `alias:port` so OLLAMA_HOST must be set for the client like this `OLLAMA_HOST=ollama:11434 ollama pull`. While the port (11434) should be exposed by default, it's possible GitLab requires it to be set explicitly.

**Comment by Bengt** [comment]
I couldn't make the service work, so for now, I am managing the Ollama server in a bash process like so:

```
pytest-python3.11:
    before_script:
        -   apt update
        -   apt install --yes curl
        -   curl https://ollama.ai/install.sh | sh
    coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
    image:
        # yamllint disable-line rule:line-length
        name: registry.gitlab.com/openknowledge-gmbh/projects/ml-platform/1-llm-chatbot:pytest-python3.11-latest
        entrypoint: [""]
    script:
        -   ollama serve &
        -   pid=$!
        -   export OLLAMA_HOST=localhost
        -   export PYTHONPATH=.
        -   cd /1-llm-chatbot
        #   Wait for ollama to start
        -   sleep 60
        -   ollama pull llama2
        -   venv/bin/python -m pytest --cov=llm_chatbot
        -   kill $pid
```

**Comment by Bengt** [comment]
Thanks for the hint, @mxyng! I think, I did that at some point, but maybe I was mistaking. I will try that again, later.

**Comment by DevOpsJeremy** [comment]
This is the solution I came up with. Run `ollama serve` as a service, then pull the model via the Ollama API in the `before_sctipt`:

```yaml
ollama:
  services:
    - name: ollama/ollama
      alias: ollama
      command: ["serve"]
  before_script:
    - curl ollama:11434/api/pull -sS -X POST -d "{\"model\":\"llama3.2\",\"stream\":false}"
  script: curl -sS ollama:11434
```
