### ISSUE TITLE
Error: error loading model /root/.ollama/models/blobs when I use any other directory for the volume.

### ISSUE THREAD

**Issue by jds11111** [ollama/ollama#2232]
I am using docker-compose to create both the server and webgui of ollama. These compile fine. Going to either port shows that both are running. There are no errors in the logs. However, if I use exec in the container, or go to a console in portainer, there are problems loading any model (I tried openchat and llama2). It downloads the files fine, but then ends with the above error statement:

```
oot@c19165979f14:~/.ollama# ollama run openchat
pulling manifest 
pulling 1cecc26325a1... 100% ▕█████████████████████████████████████████████████████████████████████████████████████████████████▏ 4.1 GB                         
pulling 43070e2d4e53... 100% ▕█████████████████████████████████████████████████████████████████████████████████████████████████▏  11 KB                         
pulling d68706c17530... 100% ▕█████████████████████████████████████████████████████████████████████████████████████████████████▏   98 B                         
pulling 415f0f6b43dd... 100% ▕█████████████████████████████████████████████████████████████████████████████████████████████████▏   65 B                         
pulling 278996753456... 100% ▕█████████████████████████████████████████████████████████████████████████████████████████████████▏  483 B                         
verifying sha256 digest 
writing manifest 
removing any unused layers 
success 
Error: error loading model /root/.ollama/models/blobs/sha256:1cecc26325a197571a1961bfacf64dc6e35e0f05faf57d3c6941a982e1eb2e1d
```

The problem seems to stem from trying to use a chosen directory to store all the data, instead of using `/data/compose`. If I use 
```
version: '3.8' 

services:
  ollama-server:
    image: ollama/ollama
    container_name: ollama-server
    volumes:
      - ./ollama:/root/.ollama
    restart: unless-stopped
    ports:
      - '11434:11434'
 ```
then I can load models fine. However, if I change that volume to something else, it fails. Changing permissions on that volume does not help.
