### ISSUE TITLE
OLLAMA_MODELS Directory

### ISSUE THREAD

**Issue by shersoni610** [ollama/ollama#2574]
Hello,

I am running Ollama on a Linus machine (zsh shell). I set the environmental variable OLLAMA_MODELS to link to an external hard drive.

export OLLAMA_MODELS=/home/akbar/Disk2/Models/Ollama/models

However, the models are still store in /usr/share/ollama/.ollama folder. I wish to store all the models to an external drive to save the
limited space on the SSD. 

Can someone help?

**Comment by ForGoodTech** [comment]
I am a newbie myself and have only 2 hours of experience on Ollama and I had the identical question as you do.

I think I have figured out the thing. Essentially, the instructions on the [FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md) works, but it may look slightly confusing because it appears to address a server configuration issue instead of `ollama run` issue.

The heart of the Ollama is the server. When you do `ollama run abc_model`, it will actually attempt to connect to the server, which manages all the models.

So, when you change your environment variables, you must let the server know one way or another. That means you must restart/reload the server.

**Option 1**. If you want to run the ollama as a service, follow the FAQ.

**Option 2**. If you want to run command lines by hand, you could do:

```
export OLLAMA_MODELS=/home/akbar/Disk2/Models/Ollama/models
# Kill the server. By the way, I don't see a command to shut down the server gracefully. 
ollama serve
ollama run whatever_model_you_want
```

**Comment by norton-chris** [comment]
I'm having a similar issue. I'm using the ollama docker container and I have it export OLLAMA_MODELS when the container is being created, but it's still not finding models when I run `ollama list` inside the container. Here is my docker-compose file:
```
services:
  ollama:
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
    volumes:
      - ollama:/root/.ollama
      - /mnt/2TB_SSD/text-gen/text-generation-webui/models:/root/.ollama/models
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
```    
When I enter the running container I echo OLLAMA_MODELS and it's correct but ollama list doesn't show any of the models. Also the default model location stated in the FAQ doesn't exist in the container. I even tried creating the default location folder and moving one of the models over, but that still doesn't work. Not sure how to restart ollama inside the ollama container to debug this.

Any help is greatly appreciated.
