### ISSUE TITLE
Error: unable to initialize llm library Radeon card detected

### ISSUE THREAD

**Issue by DocMAX** [ollama/ollama#2634]
```
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    devices:
      - /dev/dri
      - /dev/kfd
    volumes:
      - data:/root/.ollama
    restart: unless-stopped

volumes:
  data:
```

Having this docker compose config i get the following error:

```
Error: unable to initialize llm library Radeon card detected, but permissions not set up properly.  Either run ollama as root, or add you user account to the render group.
time=2024-02-21T12:25:30.862Z level=INFO source=images.go:706 msg="total blobs: 31"
time=2024-02-21T12:25:30.863Z level=INFO source=images.go:713 msg="total unused blobs removed: 0"
time=2024-02-21T12:25:30.864Z level=INFO source=routes.go:1014 msg="Listening on [::]:11434 (version 0.1.25)"
time=2024-02-21T12:25:30.864Z level=INFO source=payload_common.go:107 msg="Extracting dynamic libraries..."
Error: unable to initialize llm library Radeon card detected, but permissions not set up properly.  Either run ollama as root, or add you user account to the render group.
time=2024-02-21T12:25:43.219Z level=INFO source=images.go:706 msg="total blobs: 31"
time=2024-02-21T12:25:43.220Z level=INFO source=images.go:713 msg="total unused blobs removed: 0"
time=2024-02-21T12:25:43.221Z level=INFO source=routes.go:1014 msg="Listening on [::]:11434 (version 0.1.25)"
time=2024-02-21T12:25:43.222Z level=INFO source=payload_common.go:107 msg="Extracting dynamic libraries..."
```

I wonder how to fix the permission error. Can it be fixed in the docker compose code?
