### ISSUE TITLE
Start specific model from docker-compose

### ISSUE THREAD

**Issue by donnadulcinea** [ollama/ollama#2932]
Hello everybody. I am stuck with this issue. maybe many of you already faced and solved this. 
This is my service in docker-compose:

```
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11435:11434"
    volumes:
      - ./DockerVolumes/vol_ollama:/root/.ollama
```

I want the container to start with the **llava** model already without the need for me to connect to the shell and run it.
Which way can I do it? So far I tried adding the `command `statement, e.g.

    command: ["ollama run llava:13b"]

or

    command: ["/bin/sh", "-c", "/usr/bin/ollama run llava:13b"]

But I always receive errors like:

    2024-03-05 19:07:44 Error: unknown command "ollama" for "ollama"

or

    2024-03-05 19:07:44 Error: unknown command "/bin/sh" for "ollama"

Which way to achieve this?
