### ISSUE TITLE
docker container only listens on ipv6 by default

### ISSUE THREAD

**Issue by nopoz** [ollama/ollama#3300]
### What is the issue?

The docker container only listens on ipv6 by default. This causes connection failures for other containers in the same stack that are trying to communicate with ollama with ipv4. 

### What did you expect to see?

For the container to listen on both ipv4 and ipv6. 

### Steps to reproduce

Deploy ollama:

```
version: '3.3'
services:
    ollama:
      container_name: ollama
      volumes:
          - "/docker/ollama:/root/.ollama"
      restart: unless-stopped
      image: ollama/ollama:0.1.29
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]
```

Verify port 11434 is only listening on ipv6 inside the container:

```
~$ docker exec -t -i ollama /bin/bash
root@28988fb7b322:/# apt update
[...]
root@28988fb7b322:/# apt install net-utils
[...]
root@28988fb7b322:/# netstat -nap | grep LISTEN
tcp        0      0 127.0.0.11:35687        0.0.0.0:*               LISTEN      -
tcp6       0      0 :::11434                :::*                    LISTEN      1/ollama
```

You can workaround this issue by adding the following lined to the docker compose file:

```
      ports:
          - '127.0.0.1:11434:11434'
```

However this is problematic as it exposes the port to the entire docker host which is unnecessary. The port only needs to be exposed internally to the other containers in the same stack. 

### OS

Linux

### Architecture

amd64

### Platform

Docker, WSL2

### Ollama version

0.1.29

### GPU

Nvidia
