### ISSUE TITLE
Switching dynamically between multiple LLM models on VRAM 

### ISSUE THREAD

**Issue by Q-point** [ollama/ollama#3507]
### What are you trying to do?

At the moment, Ollama needs to load LLM one by one. It should be possible to have multiple LLM resident in VRAM memory and switch dynamically between the two.

### How should we solve this?

1. Check if the requested images can be loaded within the current hardware VRAM budget.
2. load multiple images in VRAM.
3. Augment API to switch dynamically between the two.  

### What is the impact of not solving this?

The present latency when loading and unloading multiple models.

**Comment by csely** [comment]
Ollama is small, using `docker compose` to run multiple instances may be helpful to you.

```yaml
version: '3'
services:
  ollama_1:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ./data/.ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped
  ollama_2:
    image: ollama/ollama
    ports:
      - "11435:11434"
    volumes:
      - ./data/.ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped
  #ollama_n ...

```
