### ISSUE TITLE
Can't connect to registry.ollama.ai "read: connection refused"

### ISSUE THREAD

**Issue by simonfrey** [ollama/ollama#3578]
### What is the issue?

I try to run `ollama run codegemma`, but on the `pulling manifest` stage I get the following error:

```
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/codegemma/manifests/latest": dial tcp: lookup registry.ollama.ai on 10.89.3.1:53: read udp 10.89.3.11:54907->10.89.3.1:53: read: connection refused
```

### What did you expect to see?

Running downloaded model

### Steps to reproduce

Enter `ollama run codegemma`

### Platform 

In docker

### Docker-Compose file

```yaml
version: '3'

services:
  ollama:
    image: 'docker.io/ollama/ollama:0.1.31'
    ports:
      - 11434:11434
    networks:
      - ollama-network
    volumes:
      - ./ollama/:/root/.ollama
networks:
  ollama-network:
    driver: bridge
```
