### ISSUE TITLE
During container deployment, ollama reads model files on the host very slowly

### ISSUE THREAD

**Issue by ChaoII** [ollama/ollama#4197]
### What is the issue?

When I deployed ollama in the container and hung the model path on the host, I kept loading the model files externally by accessing ollama's chat model, which was very, very slow, maybe only 20M/s. I'm using Docker Desktop, using the WSL2 backend, and the files are mounted on the SSD.

### OS

Docker

### GPU

Nvidia

### CPU

Intel

### Ollama version

all version

**Comment by ChaoII** [comment]
I've seen the FAQ, but I don't know if reading the host model file has anything to do with networking. 
```yml
services:
  ollama:
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    image: ollama/ollama
      #tty: true
    restart: always
    environment:
    - OLLAMA_ORIGINS="*"
    - OLLAMA_HOST="0.0.0.0:11434"
    ports:
      - 11434:11434
    volumes:
      - C:/Users/xx/.ollama:/root/.ollama:cached
```
