### ISSUE TITLE
Ollama Docker Container Slow Down Overtime

### ISSUE THREAD

**Issue by nycameraguy** [ollama/ollama#4846]
### What is the issue?

I am working in a multi-GPU environment.  I set up multiple docker containers to assign each GPU to it so I can process my workload in parallel.

Here is the command I use to set up the container:
`sudo docker run -d --gpus device=GPU-46b6fece-aec9-853f-0956-2d43359e28e3 -v ollama:/root/.ollama -p 11435:11434 --name ollama0 ollama/ollama`

I noticed the performance of the Ollama Docker container degrades significantly overtime. I am processing a workload with over 134,000 queries with llama3:instruct. In the beginning, the processing speed is about 1~2 items/s, after processing a few thousands of queries, it slows down to 10~12 items/s, and it gets worse over time.

If I remove the container and reconfigure the container. The performance will be back to normal. 

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.1.38

**Comment by JerryGamble1** [comment]
We are seeing the same behavior (probably irrelevant difference is that we have an Intel processor in the server).

**Comment by nycameraguy** [comment]
I suspect there might be an Nvidia driver compatibility issue. We have two A6000 48GB with 535.161.07 driver installed.
I have observed a similar issue reported by other users on Reddit. https://www.reddit.com/r/ollama/comments/1debdr7/dockerized_ollama_doesnt_use_gpu_even_though_its/

**Comment by shivakharbanda** [comment]
facing same issue help

**Comment by jessegross** [comment]
@shivakharbanda Can you provide more information about the version of Ollama that you are running and whether the Nvidia driver version in the linked thread helps?

There are some fixes in current versions that may help but it's hard to tell from the original context since this is relatively old.

**Comment by shivakharbanda** [comment]
i am using a 80 gb a100 gpu and  i am using latest ollama using 
```
docker run -d --gpus=all -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
```
btw we have switched to vllm now. its utilizing the gpu well and there is no performance issue as of now.

**Comment by neuhaus** [comment]
I have an issue where ollama in the docker container stops recognizing the nVidia card **after a while**. 
In the ollama docker log, i get this message:
`ggml_cuda_init: failed to initialize CUDA: no CUDA-capable device is detected`
whereas when it detects the card successfully, it looks like this:
```
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA RTX 4000 SFF Ada Generation, compute capability 8.9, VMM: yes

```
Restarting the docker container resolves the issue.

Here is the relevant part of my compose.yml file:
```
version: '3.8'
services:
  ollama:
    image: ollama/ollama
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    container_name: ollama
    networks:
      - ollama_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]  # enables GPU usage
    restart: unless-stopped
```

I'm using  nvidia-container-toolkit 1.17.3-1 on Ubuntu 24.04 with nvidia-driver-560 version  560.35.05-0ubuntu1.

The problem occurs so frequently that i have added a cronjob to check for the log line indicating that the hardware was not found and then automatically restarting the ollama docker container. Not a good solution.
