### ISSUE TITLE
Add Ollama config file

### ISSUE THREAD

**Issue by t18n** [ollama/ollama#4883]
I want to request a config file that allow user to manage models in the text form. This would allow us to sync in dotfiles, manage models very easily.

For example:
```yaml
// ~/.config/ollama/config.yaml

models:
  - name: llama3
  - name: llama3:70b
  - name: mistral:7b

config:
  - name: mistral
       max_input_tokens: 32000
```

Then in terminal, you can just run `ollama pull`, it will automatically pull all listed models, or `ollama purge` to clean up and keep only models in the config file

## Inspirations
https://asdf-vm.com/manage/configuration.html#tool-versions
https://mise.jdx.dev/configuration.html#mise-toml
