### ISSUE TITLE
Error: Pull Model Manifest - Timeout

### ISSUE THREAD

**Issue by ulhaqi12** [ollama/ollama#4933]
### What is the issue?

Hi,
I am using the latest docker image of Ollama(0.1.40). Here are the contents of my docker-compose file:

```
  ollama:
    image: docker-registry-remote.artifactory-espoo2.int.net.nokia.com/ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"  
    volumes:
      - ollama:/root/.ollama  
    restart: unless-stopped  
```

and I am trying to run llama3 using the following command:
```
$ sudo docker exec -it ollama  ollama pull llama3
```
Getting the following error:
```
pulling manifest
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/llama3/manifests/latest": dial tcp 104.21.75.227:443: i/o timeout
```

Can you guide me? Is this an issue with Ollama?
I have tried accessing manifest (https://registry.ollama.ai/v2/library/llama3/manifests/latest) on a web browser. Here is what it's showing me:
![image](https://github.com/ollama/ollama/assets/44068298/098b48bf-94b0-40af-a088-d27b7e170b0f)

-Ikram

### OS

Linux

### CPU

Intel

### Ollama version

0.1.40
