### ISSUE TITLE
Regression on ollama docker images >=0.1.33-rocm: rocBLAS does not find secondary GPU for Tensile

### ISSUE THREAD

**Issue by icodeforyou-dot-net** [ollama/ollama#5000]
### What is the issue?

Updating my docker stack from the ollama `0.1.32-rocm` docker image to `0.1.33-rocm` and above (tested up to `0.1.43-rocm`) leads to my secondary GPU becoming unusable for ollama with the following 

> ollama-rocm  | rocBLAS error: Could not initialize Tensile host: No devices found

The secondary GPU is a Radeon Pro W6600 and the primary GPU is a Radeon Pro W6800. The configuration that I am using is isolating the secondary GPU for use with ollama via the `ROCR_VISIBLE_DEVICES=1` environment variable. This used to work just fine with the `0.1.32-rocm` image from DockerHub (and still does).

Since I am running an identical second Radeon Pro W6600 as sole GPU in a server, neither the GPU nor the docker image itself should be the issue. In that machine everything works fine.

Most likely there is some problem with the dual GPU configuration and the way I am trying to isolate the second GPU for use with ollama. But I don't really know what it might be at this point.

Any help is very much appreciated!

Here is my `compose.yaml` file:

```yaml
services:
    ollama:
        privileged: true
        devices:
            - /dev/kfd:/dev/kfd
            - /dev/dri:/dev/dri
        volumes:
            - ollama:/root/.ollama
        ports:
            - 11434:11434
        environment:
            - OLLAMA_DEBUG=1
            - HSA_OVERRIDE_GFX_VERSION=10.3.0
            - ROCR_VISIBLE_DEVICES=1
#- GPU_MAX_HW_QUEUES=1
        container_name: ollama-rocm
        restart: always
        image: ollama/ollama:0.1.33-rocm
    open-webui:
        ports:
            - 3000:8080
        volumes:
            - open-webui:/app/backend/data
        environment:
            - OLLAMA_BASE_URLS=http://ollama-rocm:11434
        container_name: open-webui
        restart: always
        image: ghcr.io/open-webui/open-webui:main

volumes:
    ollama:
        external: false
        name: ollama
    open-webui:
        external: false
        name: open-webui
```

System info:

- Linux 6.6.32 NixOS
- Ryzen 3900X
- Dual GPU, Radeon Pro W6800 and Radeon Pro W6600

### OS

Linux

### GPU

AMD

### CPU

AMD

### Ollama version

0.1.33 and above
