### ISSUE TITLE
Add Basic Networking Tools to Docker Image for Health Checks

### ISSUE THREAD

**Issue by OlaoluwaM** [ollama/ollama#5389]
Hi! Would it be possible to include one or two network command packages like `ping`, `netcat`, or `curl` in the Docker image? This would allow folks who want to query the health check endpoint using `docker compose` or similar tools to do so without needing to create a custom `Dockerfile`.

I get that y'all are [hesitant](https://github.com/ollama/ollama/pull/1909) about adding a `HEALTHCHECK` command directly to the Dockerfile since it's not standard in any of Docker's official images. But at least with these packages, anyone wanting to set up a health check for their containers can do so more easily.

I'd be happy to open a PR for this if you think it's a good idea.

Thanks!

**Comment by rick-github** [comment]
It's possible to add a health check to a docker-compose file.  I use this for various docker images that don't contain in-image tools for testing endpoints, just set HEALTH for the port and pattern to check:

```
x-healthcheck: &healthcheck
  test: ["CMD-SHELL", "exec bash -c '
      for i in $${HEALTH-11434/:Ollama.is.running} ; do
        pat=$${i#*:} ;
        port=$${i%:*} ;
        path=$${port#*/} ;
        port=$${port%%/*} ;
        (exec 3<> /dev/tcp/localhost/$$port ;
        (echo GET /$$path HTTP/1.0 ; echo) >&3 ; cat <&3) | grep -q $$pat ||
          {
            [ $${RESTART-0} == 1 ] && { kill -s TERM -1 ; sleep 5 ; kill -s KILL -1 ; kill -s TERM 1 ; } ;
            exit 1 ;
          }
      done'"
    ]
  interval: 10s
  start_period: 10s

services:
  ollama:
    image: ollama/ollama
    healthcheck: *healthcheck
    environment:
      - HEALTH=11434/:Ollama.is.running

  litellm:
    image: litellm/litellm
    healthcheck: *healthcheck
    environment:
      - HEALTH=8000/health/liveliness:I.m.alive

```

**Comment by sinanartun** [comment]
you can just make a get request to /api/version

**Comment by nopoz** [comment]
See PR and temporary workaround for installing curl https://github.com/ollama/ollama/pull/6641#issuecomment-2430126710

**Comment by rick-github** [comment]
If users want to add tools to the docker image, just spin a new image:
```Dockerfile
FROM ollama/ollama                                                                                   
RUN apt update && apt install -y \
      curl \
      netcat \
      iputils-ping \
      && rm -rf /var/lib/apt/lists/*
```
```
$ docker build -f Dockerfile -t ollama-networktools .
$ docker run --rm -d --name ollama-networktools ollama-networktools
$ docker exec -it ollama-networktools curl localhost:11434
Ollama is running
```

**Comment by qhaas** [comment]
In docker compose (or your orchestration script of choice), could also just add a curl [service (equivalent)](https://docs.docker.com/reference/compose-file/services/) that depends on ollama to check to see if it is up using the aforementioned api status call, e.g. (haven't tested, assuming the ollama service is named ollama)
```
```yaml
ollama-up:
    image: curlimages/curl
    command: -o /dev/null -kfsS ollama:11434/api/version
    restart: on-failure
    depends_on:
      - ollama
```
Note the above approach will not tell you if the ollama service later got into a bad state since it exits as soon as it succeeds.
I'm using a similar healthcheck inside the ollama container, but I installed curl in a derived image.  The most annoying thing is the continuous spam in the ollama logs about the /api/version endpoint being hit by the healthcheck itself, which there is likely a way to disable and the use of a second curl service avoids.

**Comment by qhaas** [comment]
That is a nice solution without having to modify the base image and still be able to check for bad state.  Unfortunately, will still get a new log entry each time the healthcheck runs, which in some cases is ideal, but often is a bit too verbose.

**Comment by rick-github** [comment]
If docker compose is being used, here's a refinement to the new image workaround:
```yaml
services:
  ollama:
    image: ollama-curl:${OLLAMA_DOCKER_TAG-latest}
    build:
      dockerfile_inline: |
        FROM ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
        RUN apt update && apt install -y curl && rm -rf /var/lib/apt/lists/*
    healthcheck:
      test: curl ollama:11434
      interval: 5s
      start_period: 5s
```
This way there's no external Dockerfile to maintain.

**Comment by rick-github** [comment]
```yaml
services:
  ollama:
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    environment:
      MODEL: ${MODEL-qwen2.5:0.5b}   # this model must always be present
    healthcheck:
      test: ollama show $${MODEL}
      interval: 60s
      start_period: 5s
```
