### ISSUE TITLE
Model getting unloaded from memory every time prompt is sent

### ISSUE THREAD

**Issue by vjsyong** [ollama/ollama#5557]
### What is the issue?

With this latest version of Ollama, every time a prompt is sent to the model, the model gets unloaded from memory and needs to be reinitialised. Leading to much longer time-to-first-token responses. It's the same for every model that I've tested.

Here's what is looks like in the current version 0.2.0 docker container

![unload](https://github.com/ollama/ollama/assets/46567682/86cb0093-5a20-4033-9595-d986674ee05c)

This is what it used to be in the previous version 0.1.47 docker container

![unload_old](https://github.com/ollama/ollama/assets/46567682/02ab926a-7f46-4704-b873-c7ab852c311d)

Here's the docker compose config that I'm using

**EDIT: I had linked an older docker compose YAML file that I used for the 0.1.47 version. I've updated it to the one actually used in the problematic version. To note: `OLLAMA_NUM_PARALLEL` is set to 4 and `OLLAMA_MAX_LOADED_MODELS` is set to 2 instead of 1 and 1 as originally posted**

```
services:
  ollama:
    image: ollama/ollama:0.2.0
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    tty: true
    restart: unless-stopped
    environment:
      - OLLAMA_FLASH_ATTENTION=0
      - OLLAMA_KEEP_ALIVE=10m
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_MAX_LOADED_MODELS=2
    networks:
      - llms

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - llms

volumes:
  ollama: {}
  open-webui: {}

networks:
  llms:
    external: true
```

### OS

Docker

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.2.0
