### ISSUE TITLE
Ollama-rocm on Kubernetes with shared AMD GPU seems to have problems allocating vram

### ISSUE THREAD

**Issue by kubax** [ollama/ollama#6673]
### What is the issue?

Hi,

i'm pretty new to Ollama, and recently replaced my RX580 with a RX7600 to be able to use Ollama in Kubernetes with ROCm.

When i run Ollama on Arch directly with ROCm support everything works great and is realy snappy.

But when i run Ollama through Kubernetes with the AMD Plugin to share GPUs, it seems to not be able to allocate vram.

Here is my Kubernetes deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ollama
  name: ollama
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - env:
            - name: OLLAMA_HOST
              value: 0.0.0.0
            - name: OLLAMA_KEEP_ALIVE
              value: 24h
            - name: HSA_OVERRIDE_GFX_VERSION
              value: "10.3.0"
            - name: AMD_SERIALIZE_KERNEL
              value: "3"
            - name: OLLAMA_LLM_LIBRARY
              value: "rocm_v60002"
          # image: ollama/ollama:latest
          image: ollama/ollama:rocm
          # image: bergutman/ollama-rocm
          name: ollama
          ports:
            - containerPort: 11434
              hostPort: 7869
              protocol: TCP
          tty: true
          volumeMounts:
            - mountPath: /code
              name: ollama-claim0
            - mountPath: /root/.ollama
              name: ollama-claim1
          resources:
            limits:
              amd.com/gpu: 1 # requesting a GPU
      restartPolicy: Always
      volumes:
        - name: ollama-claim0
          persistentVolumeClaim:
            claimName: ollama-claim0
        - name: ollama-claim1
          persistentVolumeClaim:
            claimName: ollama-claim1
``` 

When Ollama tries to load the modle into vram nvtop does report 0byte vram usage and Ollama crashes with a segfault.

Here are the last lines wich seem to be interessting to me.

```
time=2024-09-06T10:51:05.040+02:00 level=INFO source=server.go:625 msg="waiting for server to become available" status="llm server loading model"
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 ROCm devices:
  Device 0: AMD Radeon™ RX 7600 XT, compute capability 10.3, VMM: no
llm_load_tensors: ggml ctx size =    0.27 MiB
time=2024-09-06T10:51:46.399+02:00 level=INFO source=server.go:625 msg="waiting for server to become available" status="llm server not responding"
time=2024-09-06T10:51:47.553+02:00 level=ERROR source=sched.go:456 msg="error loading llama server" error="llama runner process has terminated: signal: segmentation fault (core dumped)"
[GIN] 2024/09/06 - 10:51:47 | 500 | 43.035446402s |       127.0.0.1 | POST     "/api/chat"
time=2024-09-06T10:51:52.553+02:00 level=WARN source=sched.go:647 msg="gpu VRAM usage didn't recover within timeout" seconds=5.000619052 model=/root/.ollama/models/blobs/sha256-8934d96d3f08982e95922b2b7a2c626a1fe873d7c3b06e8e56d7bc0a1fef9246
time=2024-09-06T10:51:52.803+02:00 level=WARN source=sched.go:647 msg="gpu VRAM usage didn't recover within timeout" seconds=5.250422078 model=/root/.ollama/models/blobs/sha256-8934d96d3f08982e95922b2b7a2c626a1fe873d7c3b06e8e56d7bc0a1fef9246
time=2024-09-06T10:51:53.054+02:00 level=WARN source=sched.go:647 msg="gpu VRAM usage didn't recover within timeout" seconds=5.500667507 model=/root/.ollama/models/blobs/sha256-8934d96d3f08982e95922b2b7a2c626a1fe873d7c3b06e8e56d7bc0a1fef9246
[GIN] 2024/09/06 - 11:13:11 | 200 |      46.378µs |       127.0.0.1 | GET      "/api/version"
```

Is there something i can try to fix this?

### OS

Linux, Docker

### GPU

AMD

### CPU

AMD

### Ollama version

0.3.9
