### ISSUE TITLE
Is it possible to configure ollama deployed in docker?

### ISSUE THREAD

**Issue by wizounovziki** [ollama/ollama#6799]
I pull docker image from dockerhub and launched a few models and then found the num of user requests was limited.
In the documentation it shows that this could be solved by set up OLLAMA_NUM_PARALLEL by systemctl commands.
How can I do this since systemctl is not included in the docker container?

**Comment by rick-github** [comment]
Plain docker:
```
docker run -d -v ollama:/root/.ollama -p 11434:11434 -e OLLAMA_NUM_PARALLEL=2 --name ollama ollama/ollama
```
Docker compose:
```yaml
services:
  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    environment:
      - OLLAMA_NUM_PARALLEL=2 
```
