### ISSUE TITLE
Idea: Model Pre-Pulling on Startup

### ISSUE THREAD

**Issue by adrianliechti** [ollama/ollama#6815]
To ease Docker/Kubernetes based deployments, I would suggest a feature to auto download/update models on startup if not yet existing. See here a poor man implementation of that idea: https://github.com/adrianliechti/ollama/blob/main/main.go.
I could imagine this would also help in samples/documentations.

If you think that this is a good idea but no resources; I could try a proposal.
Probably the biggest challenge is naming the env variable :)

Cheers, Adrian

**Comment by rick-github** [comment]
You can do this with a compose file:
```yaml
x-ollama: &ollama
  image: ollama/ollama
  volumes:
    - ./ollama:/root/.ollama

services:
  ollama-init:
    << : *ollama
    restart: no
    entrypoint: bash -c "ollama serve & sleep 10 ; ollama pull ${MODEL-qwen2:0.5b}"

  ollama:
    << : *ollama
    depends_on:
      ollama-init:
        condition: service_completed_successfully

```
