### ISSUE TITLE
Ollama Fails to Start On Ubuntu Server OS (Headless) when using a GPU

### ISSUE THREAD

**Issue by F1zzyD** [ollama/ollama#7283]
### What is the issue?

Ollama fails to load using docker-compose on a headless Ubuntu server. I have installed, purged, reinstalled, purged, and re-reinstalled drivers, docker, docker-compose, etc. and nothing allows Ollama to boot. Here is my compose.yml:
services:
```
  ollama:
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - /home/admin/services/ollama:/root/.ollama
    restart: unless-stopped
    image: ollama/ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER-nvidia}
              count: all
              capabilities:
                - gpu
```

When using `docker compose up -d` I get this output:

```
Failed to deploy a stack: Network ollamatest_default Creating Network ollamatest_default Created Container ollama Creating Container ollama Created Container ollama Starting Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy' nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown 
```

I have used Ollama on the desktop version of Ubuntu with zero issues, but it seems that Ollama does not work on a headless version of Ubuntu, which is rather silly.

### OS

Linux

### GPU

Nvidia

### CPU

AMD

### Ollama version

latest
