### ISSUE TITLE
gpu VRAM usage didn't recover within timeout

### ISSUE THREAD

**Issue by s1s1fo** [ollama/ollama#7654]
### What is the issue?

I'm facing this error and feeling a bit lost. Apologies if the issue is on my end—I’d really appreciate any guidance.

`gpu VRAM usage didn't recover within timeout`

My docker-compose:

```
 ollama:
    image: ollama/ollama:latest
    container_name: ollama
    hostname: ollama
    ports:
      - '11434:11434'
    # VOLUMES
    # --------------------------------------------------------------------------------------------
    volumes:
      - $MODELS_DIR/ollama:/root/.ollama/models
    # NVIDIA GPU Deployment
    # --------------------------------------------------------------------------------------------
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu,compute, utility]
```

The whole log for reference:

```
    time=2024-11-13T17:36:49.865Zlevel=INFOsource=server.go:383msg=starting llama servercmd=/usr/lib/ollama/runners/cuda_v12/ollama_llama_server --model /root/.ollama/models/blobs/sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa --ctx-size 8192 --batch-size 512 --n-gpu-layers 33 --threads 16 --parallel 4 --port 38267

    time=2024-11-13T17:36:49.865Zlevel=INFOsource=sched.go:449msg=loaded runnerscount=1

    time=2024-11-13T17:36:49.865Zlevel=INFOsource=server.go:562msg=waiting for llama runner to start responding

    time=2024-11-13T17:36:49.865Zlevel=WARNsource=server.go:569msg=client connection closed before server finished loading, aborting load

    time=2024-11-13T17:36:49.865Zlevel=ERRORsource=sched.go:455msg=error loading llama servererror=timed out waiting for llama runner to start: context canceled

[GIN] 2024/11/13 - 17:36:49 | 499 |  167.145804ms |      172.27.0.2 | POST     "/v1/chat/completions"

    time=2024-11-13T17:36:49.899Zlevel=INFOsource=runner.go:863msg=starting go runner

    time=2024-11-13T17:36:49.899Zlevel=INFOsource=runner.go:864msg=systeminfo=AVX = 1 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 0 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | RISCV_VECT = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | cgo(gcc)threads=16

    time=2024-11-13T17:36:49.899Zlevel=INFOsource=.:0msg=Server listening on 127.0.0.1:38267

llama_model_loader: loaded meta data with 22 key-value pairs and 291 tensors from /root/.ollama/models/blobs/sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = Meta-Llama-3-8B-Instruct
llama_model_loader: - kv   2:                          llama.block_count u32              = 32
llama_model_loader: - kv   3:                       llama.context_length u32              = 8192
llama_model_loader: - kv   4:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   7:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   8:                       llama.rope.freq_base f32              = 500000.000000
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                          general.file_type u32              = 2
llama_model_loader: - kv  11:                           llama.vocab_size u32              = 128256
llama_model_loader: - kv  12:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv  13:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  14:                         tokenizer.ggml.pre str              = llama-bpe

    time=2024-11-13T17:36:54.937Zlevel=WARNsource=sched.go:646msg=gpu VRAM usage didn't recover within timeoutseconds=5.071643258model=/root/.ollama/models/blobs/sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa

    time=2024-11-13T17:36:55.187Zlevel=WARNsource=sched.go:646msg=gpu VRAM usage didn't recover within timeoutseconds=5.322169862model=/root/.ollama/models/blobs/sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa

    time=2024-11-13T17:36:55.437Zlevel=WARNsource=sched.go:646msg=gpu VRAM usage didn't recover within timeoutseconds=5.571735702model=/root/.ollama/models/blobs/sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa
```

### OS

Docker

### GPU

Nvidia

### CPU

AMD

### Ollama version

0.4.1
