### ISSUE TITLE
I hope that ollama can optimize the parallel performance of CPU computations?

### ISSUE THREAD

**Issue by CarsonJiang** [ollama/ollama#7827]
When serving as the LLM provider for GraphRAG, the 100% single CPU usage is preventing full utilization of multiple GPU resources on the server.

![ollama_graphrag_low_util](https://github.com/user-attachments/assets/2bbb1b65-e63a-480c-ad5e-ee17fc4723a1)

settings.yaml
```
### This config file contains required core defaults that must be set, along with a handful of common optional settings.
### For a full list of available settings, see https://microsoft.github.io/graphrag/config/yaml/

### LLM settings ###
## There are a number of settings to tune the threading and token limits for LLM calls - check the docs.

encoding_model: cl100k_base # this needs to be matched to your model!

llm:
  api_key: ollama # set this in the generated .env file
  type: openai_chat # or azure_openai_chat
  model: llama3.2
  model_supports_json: true # recommended if this is available for your model.
  # audience: "https://cognitiveservices.azure.com/.default"
  api_base: http://localhost:11434/v1
  request_timeout: 1800.0
  max_tokens: 8000

parallelization:
  stagger: 0.3
  # num_threads: 50

async_mode: threaded # or asyncio

embeddings:
  async_mode: threaded # or asyncio
  vector_store:
    type: lancedb
    db_uri: 'output/lancedb'
    container_name: default
    overwrite: true
  llm:
    api_key: ollama
    type: openai_embedding # or azure_openai_embedding
    model: nomic-embed-text:latest
    api_base: http://localhost:11434/v1
    request_timeout: 1800.0
```
