### ISSUE TITLE
mllama doesn't support parallel requests yet - llama3.2-vision:11b for Standard_NC24ads_A100_v4

### ISSUE THREAD

**Issue by breddy-lgamerica** [ollama/ollama#8186]
### What is the issue?

We are running ollama container in a kubernetes cluster in azure using Standard_NC24ads_A100_v4 and running a model mllama llama3.2-vision:11b , we keep getting the error - mllama doesn't support parallel requests yet

How do we fix this

### OS

Linux, Docker

### GPU

Nvidia

### Ollama version

0.5.4-0-g2ddc32d-dirty

**Comment by rick-github** [comment]
Do you need to do parallel requests?  If not, set `OLLAMA_NUM_PARALLEL=1`.  If you do, currently you will have to run multiple servers and offer a uniform interface with a reverse proxy (eg [litellm](https://github.com/BerriAI/litellm), [ollama_proxy](https://github.com/ParisNeo/ollama_proxy_server), [nginx](https://github.com/ollama/ollama/issues/7570#issuecomment-2464469733)).

**Comment by pdevine** [comment]
This is expected behavior right now (no support for parallel request for mllama). It's something we're looking at w/ the new engine.

**Comment by breddy-lgamerica** [comment]
Thanks for the reply @pdevine  @rick-github 

My compute is of the following configuration, how many instances of **llama3.2-vision:11b** can i run on this machine? Can you please help

	vCPUs (Qty.) 24	
	Memory (GB) 220
	Accelerators (Qty.) 1
	Accelerator-Memory (GB) 80

**Comment by rick-github** [comment]
llama3.2-vision:11b with default context and `OLLAMA_NUM_PARALLEL=1` takes about 12GB, so you could run around 6 instances.
```yaml
x-ollama: &ollama
  image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
  volumes:
    - ${OLLAMA_MODELS-./ollama}:/root/.ollama
  environment:
    - OLLAMA_KEEP_ALIVE=${OLLAMA_KEEP_ALIVE--1}
    - OLLAMA_LOAD_TIMEOUT=${OLLAMA_LOAD_TIMEOUT-5m}
    - OLLAMA_MAX_LOADED_MODELS=1
    - OLLAMA_NUM_PARALLEL=1
    - OLLAMA_TMPDIR=/tmp/ollama
    - OLLAMA_FLASH_ATTENTION=${OLLAMA_FLASH_ATTENTION-0}
    - OLLAMA_DEBUG=${OLLAMA_DEBUG-1}
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

services:
  ollama-1:
    << : *ollama

  ollama-2:
    << : *ollama

  ollama-3:
    << : *ollama

  ollama-4:
    << : *ollama

  ollama-5:
    << : *ollama

  ollama-6:
    << : *ollama

  ollama:
    image: nginx-lb
    build:
      dockerfile_inline: |
        FROM nginx:latest
        RUN cat > /etc/nginx/conf.d/default.conf <<EOF
        upstream ollama_group {
          least_conn;
          server ollama-1:11434 max_conns=8;
          server ollama-2:11434 max_conns=8;
          server ollama-3:11434 max_conns=8;
          server ollama-4:11434 max_conns=8;
          server ollama-5:11434 max_conns=8;
          server ollama-6:11434 max_conns=8;
        }
        server {
          listen 11434;
          server_name localhost;
          location / {
            proxy_pass http://ollama_group;
          }
        }
        EOF
    ports:
      - 11434:11434
```
You should probably make the mount points read-only for all but one of the ollama servers, and add control around restarts, etc.
