### ISSUE TITLE
Runing ollama on Intel Ultra NPU or GPU

### ISSUE THREAD

**Issue by jackphj** [ollama/ollama#8281]
After I installed ollama through ollamaSetup, I found that it cannot use my gpu or npu. How to solve this problem?

CPU: intel ultra7 258v
System: windows 11 24h2

**Comment by ddpasa** [comment]
With Vulkan you can at least use the GPU.  But unfortunately the Ollama team is ignoring the PR.  You can use this branch if you are interested: https://github.com/ollama/ollama/pull/5059

**Comment by ddpasa** [comment]
> Hi [@jackphj](https://github.com/jackphj)
> 
> You can try to run Ollama with IPEX-LLM on Intel GPU by referring to this link https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/ollama_quickstart.md
> 
> If you have further question on how to use this, please let me know.
> 
> Thanks and have a nice day!

With all due respect, this is almost unusable.  If Intel is serious about this, they need to merge this into ollama main so that it becomes easy to use.

**Comment by NeoZhangJianyu** [comment]
I will restore to support Intel GPU by llama.cpp SYCL backend after the current refactor is finished.
Here is the issue to track the job: https://github.com/ollama/ollama/issues/8414

**Comment by iqbalsyamsu** [comment]
I'm waiting for ollama to be able to run using NPU. It's useless to have Intel core ultra series but can't be used for further neural processes.

**Comment by Tritonio** [comment]
> I'm waiting for ollama to be able to run using NPU. It's useless to have Intel core ultra series but can't be used for further neural processes.

I think the SYCL backend mentioned above can take advantage of Intel NPUs as well, @NeoZhangJianyu would be able to confirm or deny. In some LinusTT review of the Ultra CPUs I think I heard that their NPU is not a faster way to run LLMs but it's a very power efficient way, which is great, because it won't heat up my laptop nor kill the battery that much. But the iGPU on the Ultra will be able to run inference much faster than either CPU or NPU, so I'll be happy even if Ollama supports just the iGPU on Intel Ultras, though having the NPU too would be stellar.

**Comment by tetsuo974** [comment]
Did you try export OLLAMA_DEVICE=npu

**Comment by JoseMariaZ** [comment]
You can try this:

https://github.com/JoseMariaZ/Intelexia

**Comment by JaMeyerUnica** [comment]
Install Intel oneAPI:

# Download from Intel oneAPI Base Toolkit
# Includes SYCL runtime for NPU
Set environment variables:

export ONEAPI_DEVICE_SELECTOR=sycl
export SYCL_DEVICE_FILTER=ext_oneapi_npu
Run Ollama with NPU:

ollama serve --device-type npu

should work, at least by my laptop hp elite intel evo

**Comment by JaMeyerUnica** [comment]
https://www.intel.com/content/www/us/en/content-details/826081/running-ollama-with-open-webui-on-intel-hardware-platform.html 

here a manual from intel

**Comment by anime-shed** [comment]
a good step but installing a 15GB bundle to make it works feels like a overkill

<img width="1190" height="476" alt="Image" src="https://github.com/user-attachments/assets/8010c431-878b-4216-89b0-3d70376298a4" />

Hope this can be minimized or become a part of the ollama itself.

**Comment by JaMeyerUnica** [comment]
Hi indeed but you should only need the deep learning extension, is 1,5Gb. This is info from Intel!!! I have it running fully installed, biggest problem is that they sell stuff what’s not used from programs, oh i correct Adobe sh…t 😂.
Disclaimer: i never know anything about Intel and 3rd party!!!  Not for home use 😂😈

**Comment by JaMeyerUnica** [comment]
Ps AMD same only one is ARM but this is screaming in the church ✌️

**Comment by AlyShmahell** [comment]
> Install Intel oneAPI:
> 
> # Download from Intel oneAPI Base Toolkit
> # Includes SYCL runtime for NPU
> Set environment variables:
> 
> export ONEAPI_DEVICE_SELECTOR=sycl export SYCL_DEVICE_FILTER=ext_oneapi_npu Run Ollama with NPU:
> 
> ollama serve --device-type npu
> 
> should work, at least by my laptop hp elite intel evo

would this work as an env variable in docker compose?

something like

```yml
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-intel-gpu
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - render
      - video
    environment:
      ONEAPI_DEVICE_SELECTOR: sycl # or level_zero:gpu
      SYCL_DEVICE_FILTER: ext_oneapi_npu
      SYCL_CACHE_PERSISTENT: "1"
      OMP_NUM_THREADS: "8"
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
volumes:
  ollama:
```

I cannot test it at the moment, I'm still eyeing a lunarlake device and I'm really interested, I just put this together from what I gathered from the issues.
