### ISSUE TITLE
Multi GPU, default GPU setting, specific model pin to specific GPU

### ISSUE THREAD

**Issue by dariuszsekula** [ollama/ollama#8430]
I have a multi GPU configuration and they are different GPU models with different memory size.
I wish:
1. we could select default GPU for all models (potentially the fastest one with higher memory)
2. we could select specific model per specific GPU to use small models into small VRAM GPU and use fastest/highest_VRAM card for other large models.

**Comment by rick-github** [comment]
Related: https://github.com/ollama/ollama/issues/3902

**Comment by dariuszsekula** [comment]
Thanks,
I am going to buy 5090 and I wish to have much more control over my GPUs and utilize them more efficiently.
Ollama and whole concept of deployment is amazing and more and more people will actually use it for private AI agent, instead of subscription based AI solution with risk of data to be leaked or misused.

**Comment by rick-github** [comment]
It will probably be a while before #3902 sees any progress.  In the meantime, you can sort of do this by running multiple ollama servers, binding a specific GPU to a server with `CUDA_VISIBLE_DEVICES` and then running a proxy in front to distribute the queries.  [litellm](https://github.com/BerriAI/litellm) is an LLM proxy that can route queries based on the model name.  If docker is available it's pretty easy to do a proof-of-concept.  Here I've assumed 2 GPUs: GPU0 has lots of VRAM and will run `big-model` (actually `qwen2.5:0.5b` in ollama), and GPU1 is set as the default for all other models.

```yaml
x-ollama: &ollama
  image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
  volumes:
    - ${OLLAMA_MODELS-./ollama}:/root/.ollama
  environment: &env
    OLLAMA_KEEP_ALIVE: ${OLLAMA_KEEP_ALIVE--1}
    OLLAMA_LOAD_TIMEOUT: ${OLLAMA_LOAD_TIMEOUT-5m}
    OLLAMA_MAX_LOADED_MODELS: 1
    OLLAMA_NUM_PARALLEL: 1
    OLLAMA_TMPDIR: /tmp/ollama
    OLLAMA_FLASH_ATTENTION: ${OLLAMA_FLASH_ATTENTION-0}
    OLLAMA_DEBUG: ${OLLAMA_DEBUG-1}
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            capabilities: [gpu]

services:
  ollama-1:
    << : *ollama
    environment:
      << : *env
      CUDA_VISIBLE_DEVICES: 0

  ollama-2:
    <<: *ollama
    environment:
      <<: *env
      CUDA_VISIBLE_DEVICES: 1
      OLLAMA_MAX_LOADED_MODELS: 4

  litellm:
    image: litellm-lb
    build:
      dockerfile_inline: |
        FROM litellm/litellm:${LITELLM_DOCKER_TAG-v1.58.2}
        RUN cat > /config.yaml <<EOF
        model_list:
          - model_name: big-model
            litellm_params:
              model: ollama/qwen2.5:0.5b
              api_base: http://ollama-1:11434
          - model_name: "*"
            litellm_params:
              model: "ollama/*"
              api_base: http://ollama-2:11434
        litellm_settings:
          drop_params: True
        EOF
        CMD [ "--config", "/config.yaml", "--port", "4040" ]
    ports:
      - 4040:4040
    depends_on:
      - ollama-1
      - ollama-2
```
```console
$ curl -s localhost:4040/v1/chat/completions -H "Content-Type: application/json" -d '{"model":"big-model","messages":[{"role":"user","content":"2+2?"}]}' | jq
{
  "id": "chatcmpl-7860f649-b125-4733-8722-ebdaaf70d968",
  "created": 1737047060,
  "model": "ollama/qwen2.5:0.5b",
  "object": "chat.completion",
  "system_fingerprint": null,
  "choices": [
    {
      "finish_reason": "stop",
      "index": 0,
      "message": {
        "content": "2 + 2 equals 4.\n\nThis is a simple arithmetic operation that involves two numbers (2 and 2), where we add them together to get the sum.",
        "role": "assistant",
        "tool_calls": null,
        "function_call": null
      }
    }
  ],
  "usage": {
    "completion_tokens": 35,
    "prompt_tokens": 36,
    "total_tokens": 71,
    "completion_tokens_details": null,
    "prompt_tokens_details": null
  }
}
```
```console
$ curl -s localhost:4040/v1/chat/completions -H "Content-Type: application/json" -d '{"model":"llama3.2","messages":[{"role":"user","content":"2+2?"}]}' | jq
{
  "id": "chatcmpl-14a252dd-564e-4b1a-9cc3-1e6269de28fc",
  "created": 1737047497,
  "model": "ollama/llama3.2",
  "object": "chat.completion",
  "system_fingerprint": null,
  "choices": [
    {
      "finish_reason": "stop",
      "index": 0,
      "message": {
        "content": "The answer is: 4",
        "role": "assistant",
        "tool_calls": null,
        "function_call": null
      }
    }
  ],
  "usage": {
    "completion_tokens": 7,
    "prompt_tokens": 32,
    "total_tokens": 39,
    "completion_tokens_details": null,
    "prompt_tokens_details": null
  }
}
```
The restriction is that you have to use the OpenAI to talk to the proxy, so some of the fancier ollama options like creating models are not available.
