### ISSUE TITLE
error "cudaMalloc failed: out of memory"; can't configure Ollama to valid CPU/GPU offloading

### ISSUE THREAD

**Issue by SlavikCA** [ollama/ollama#8447]
### What is the issue?

System:
- Ubuntu 22 server with Docker
- 640GB RAM
- Nvidia RTX 3090 with 24GB VRAM
- 2x Intel Xeon Gold 5218

Docker compose:
```
services:
  ollama:
    image: ollama/ollama:0.5.6
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - 11434:11434
    tty: true
    environment:
      - 'OLLAMA_FLASH_ATTENTION=1'  # only GPUs with compute capability 7+ support flash attention
      - 'OLLAMA_KV_CACHE_TYPE=q8_0' # Quantization type for the K/V cache (default: f16)
      - 'OLLAMA_NUM_PARALLEL=1'     # The maximum number of parallel requests each model will process at the same time
      - 'OLLAMA_GPU_OVERHEAD=8G'    # Reserve a portion of VRAM per GPU (bytes)
```

Steps:
- download Deepseek V3 model (default q4_K_M quantization)
- run the query

Error:

ollama  | ggml_cuda_init: found 1 CUDA devices:
ollama  |   Device 0: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
ollama  | time=2025-01-16T04:29:50.986Z level=INFO source=runner.go:937 msg=system info="CUDA : ARCHS = 600,610,620,700,720,750,800,860,870,890,900 | USE_GRAPHS = 1 | PEER_MAX_BATCH_SIZE = 128 | CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | LLAMAFILE = 1 | AARCH64_REPACK = 1 | cgo(gcc)" threads=16
ollama  | time=2025-01-16T04:29:50.987Z level=INFO source=.:0 msg="Server listening on 127.0.0.1:45667"
ollama  | llama_load_model_from_file: using device CUDA0 (NVIDIA GeForce RTX 3090) - 23891 MiB free
ollama  | llama_model_loader: loaded meta data with 42 key-value pairs and 1025 tensors from /root/.ollama/models/blobs/sha256-d83c18fb2a2ccca56d641920f01e6fe533dfb3fcf4b77c007c931497cd24a517 (version GGUF V3 (latest))
...
ollama  | ggml_backend_cuda_buffer_type_alloc_buffer: allocating 35533.34 MiB on device 0: cudaMalloc failed: out of memory
ollama  | llama_model_load: error loading model: unable to allocate CUDA0 buffer
ollama  | llama_load_model_from_file: failed to load model
ollama  | panic: unable to load model: /root/.ollama/models/blobs/sha256-d83c18fb2a2ccca56d641920f01e6fe533dfb3fcf4b77c007c931497cd24a517
ollama  | 
ollama  | goroutine 7 [running]:
ollama  | github.com/ollama/ollama/llama/runner.(*Server).loadModel(0xc0000be1b0, {0x5, 0x0, 0x1, 0x0, {0x0, 0x0, 0x0}, 0xc000026200, 0x0}, ...)
ollama  | 	github.com/ollama/ollama/llama/runner/runner.go:852 +0x3ad
ollama  | created by github.com/ollama/ollama/llama/runner.Execute in goroutine 1
ollama  | 	github.com/ollama/ollama/llama/runner/runner.go:970 +0xd0d
ollama  | time=2025-01-16T04:30:11.539Z level=INFO source=server.go:589 msg="waiting for server to become available" status="llm server error"
ollama  | time=2025-01-16T04:30:11.790Z level=ERROR source=sched.go:455 msg="error loading llama server" error="llama runner process has terminated: error loading model: unable to allocate CUDA0 buffer\nllama_load_model_from_file: failed to load model"

I tried `OLLAMA_GPU_OVERHEAD` with 8G, and without `OLLAMA_GPU_OVERHEAD` - same result. Looks like `OLLAMA_GPU_OVERHEAD` doesn't do anything.

I can run the model WITHOUT GPU. It works. Can't offload anything on it.

With GPU, according to logs above it tried to use 35GB of VRAM, when I only have 24GB.

Is there a way to configure Ollama to better calculate VRAM allocation?

### Ollama version

0.5.6
