### ISSUE TITLE
cannot find ROCM files/tools in docker image

### ISSUE THREAD

**Issue by nicoKoehler** [ollama/ollama#8518]
I was trying to figure out which ROCM version the image was using (trying to get faster-whisper to run in docker too, so I thought this could be a lead) and could not find anything. Where would they be? Why arent there any of the typical files and folders?

System: Docker on Debian  12.5, 16GB, AMD RX 550 4GB
Docker image: ollama/ollama:rocm

Docker-compose
```
services:

  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    environment:
      OLLAMA_MODELS: /usr/share/ollama
      HSA_OVERRIDE_GFX_VERSION: "11.0.0"
      HIP_VISIBLE_DEVICES: "0"
    devices:
      - "/dev/kfd"
      - "/dev/dri"
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    ipc: host
    group_add:
      - video
    volumes:
      - /home/username/.ollama:/root/.ollama
      - /home/username/ollama/models:/usr/share/ollama
    ports:
      - "11434:11434"
```

Running
`find / -type d -name "*rocm*" 2>/dev/null`

Turned up `/usr/lib/ollama/runners/rocm_avx` but could not find anything there.
