### ISSUE TITLE
High idle power consumption due to persistent CUDA initialization

### ISSUE THREAD

**Issue by SvenMeyer** [ollama/ollama#8591]
### What is the issue?

# High idle power consumption due to PCIe bus unable to enter sleep state

## Issue Description
When running Ollama as a service with CUDA enabled, the system maintains unnecessarily high power consumption (~14W vs ~6W) even when idle. This is primarily caused by the PCIe bus being unable to enter sleep state (D3) due to persistent CUDA initialization, despite the GPU itself being in a low-power state.

### Technical Details
- System: DELL XPS15 9530
- CPU: Intel i7-13700H
- GPU: NVIDIA RTX 4070 Laptop
- Driver Version: 550.144.03
- CUDA Version: 12.4
- Ollama Version: 0.5.7
- OS: Manjaro Linux (DISTRIB_RELEASE="24.2.1")
- Kernel: Linux 6.12.4-1-MANJARO

### Current Behavior
Power consumption breakdown:
- Base system (no Ollama): ~6W
- With Ollama service running: ~14W
- Delta: ~8W additional power

The increased power consumption is primarily due to:
1. PCIe bus stuck in D0 state (cannot enter D3 sleep)
2. CUDA runtime keeping PCIe link active

The GPU itself is actually well-behaved:
- Enters P8 power state correctly
- Only draws ~4W at idle
- Properly releases display to Intel GPU
- Memory Usage: 11MiB

### Expected Behavior
- PCIe bus should enter D3 state when CUDA inference is not active
- System should maintain low power consumption (~6W) when not actively processing
- CUDA initialization should happen only when needed for inference
- No impact on inference performance when needed

### Diagnostics
With Ollama service running but idle:
```
PCIe State: D0 (should be D3)
GPU Power State: P8
GPU Power Draw: ~4W
Display: Using Intel GPU
CUDA: Initialized but idle
```

### Attempted Solutions
1. CUDA environment configuration:
```ini
Environment="CUDA_MODULE_LOADING=LAZY"
Environment="CUDA_CACHE_DISABLE=0"
Environment="NVIDIA_DRIVER_CAPABILITIES=compute,utility"
```

2. PCIe power management:
```bash
echo auto > /sys/bus/pci/devices/0000:01:00.0/power/control
```

3. Various NVIDIA power management settings through nvidia-smi

None of these solutions allowed the PCIe bus to enter sleep state while the Ollama service is running.

### Proposed Solution
Implement lazy CUDA initialization in Ollama:
1. Initialize CUDA only when a model is loaded/inference requested
2. Release CUDA context when idle for a configurable period
3. Allow PCIe bus to enter D3 state when CUDA context is released
4. Add configuration option for power management strategy

Benefits:
- Lower idle power consumption
- Better battery life on laptops
- Same performance for actual inference
- No impact on API responsiveness
- Proper power management for PCIe bus

### Current Workaround
Users need to manually start/stop the Ollama service when needed:
```bash
sudo systemctl start ollama  # When inference needed
sudo systemctl stop ollama   # To restore low power state
```

This is not ideal for IDE integrations and other automated workflows that expect Ollama to be always available.

Would you consider implementing lazy CUDA initialization to allow proper PCIe power management while maintaining performance?

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.5.7

**Comment by rick-github** [comment]
Unload the model if it's idle.  `OLLAMA_KEEP_ALIVE=5m`.

**Comment by SvenMeyer** [comment]
> Unload the model if it's idle. `OLLAMA_KEEP_ALIVE=5m`.

Thanks, will try that.

Should I use the `ollama-cuda` or `ollama-cuda-git` version or should I be fine just executing `install.sh` which worked actually fine for me except for the power issue mentioned above.

**Comment by rick-github** [comment]
`install.sh` should be good enough.  For maximum power saving you can set `OLLAMA_KEEP_ALIVE=0`, that will cause the model to be immediately unloaded after inference.  This does mean that there will be a slight delay for inference as the model needs to be reloaded into the GPU.  Since the model is likely already in the page cache the delay should be small; if the model has been evicted from the page cache ollama will need to load from disk and the startup time will be longer.

It's possible that the savings from this may not be as great as stopping the service - the ollama server probes the CUDA devices to know what it can use, if that causes D0 state in the PCIe bus then there will still be some power draw even if no model is loaded.

**Comment by SvenMeyer** [comment]
Here's a summary of our findings regarding Ollama's power consumption:

### Root Cause Analysis
- Primary power drain comes from **PCIe bus** being stuck in D0 state (~8W overhead)
- GPU itself behaves well:
  - Enters P8 power state correctly
  - Only draws ~4W at idle
  - Properly releases display to Intel GPU

### Power States
- Ollama service not running  (hybrid mode - no network) : ~ 3.5W
- Ollama service running idle (hybrid mode - no network) : ~12.8W 

### Testing OLLAMA_KEEP_ALIVE=0
- Setting did not significantly impact idle power consumption
- PCIe bus remains in D0 state
- Still consumes ~8W more power when service is running
- The only solution remains to stop the Ollama service completely

### Our Solution
We developed a power management approach (https://github.com/SvenMeyer/dell-xps15-cuda-ollama-setup) that:
1. Boots in hybrid mode (allows GPU switching)
2. Keeps Ollama service disabled by default
3. Provides `opm` tool for on-demand service control
4. Achieves minimum idle power while maintaining flexibility

### Potential Improvements for Ollama
1. **Current Workaround**: 
   - Set `OLLAMA_KEEP_ALIVE=0` (suggested by Ollama team)
   - Models unload immediately after inference
   - Slight delay for model reloading

2. **Ideal Solution** would involve:
   - Lazy CUDA initialization (only when needed)
   - Allow PCIe bus to enter D3 state when idle
   - Maintain API availability without power penalty
   - Smart model caching with power awareness

**Comment by evgeniy-harchenko** [comment]
It's a really big problem. My idle power consumption is around 80W. I'm using Open WebUI, so I can't stop and start Ollama every time I want to use it.

As a temporary solution I created proxy for switching GPU/CPU: [link](https://gist.github.com/evgeniy-harchenko/0500161ec9a3345ea8972c27b2448271)

_I don't work with python at all, so fixes and suggestions are welcome._

But I would really like to see an official solution to this problem. It would be very helpful. I believe the developers will be able to figure it out.

**Comment by diba78** [comment]
Hello everybody,

i have the same problem with the following system:

Technical Details
System: Asrock n100m
CPU: Intel n100
GPU: NVIDIA RTX 3060 or 4080
Driver Version: 580.126.09
CUDA Version: 13.0
Ollama Version: 0.15.4
OS: Ubuntu Server Linux (DISTRIB_RELEASE="24.04.3 LTS")
Kernel: Linux 6.8.0-94-generic

**Comment by JamesJi79** [comment]
I was surprised how much power idle CUDA burns too. I ended up measuring my whole setup with a watt meter and a 4090 idling after inference was pulling about 22W just from the PCIe bus staying active. Has anyone here looked at whether running a lower-power card like a T4 or L40S for always-on setups makes sense, or is the inference speed drop too much to be worth it?

**Comment by serhiiz** [comment]
I'm experiencing the same issue. Tesla V100 in R730xd consumes 40W with idle ollama; and 27W without. In my case, I'm more concerned about the extra noise from chassis fans that need to spin at higher rpm.

**Comment by mgifford** [comment]
The idle power draw isn't just a laptop battery issue; it's a massive sustainability problem for self-hosted AI stacks running 24/7.

To help with this, could we expose a strict API endpoint (e.g., POST /api/sleep) that forcibly unloads all models from VRAM and releases the [CUDA locks](https://www.softwareseni.com/cuda-lock-in-unpacked-the-software-moat-the-real-switching-costs-and-how-they-are-changing/)? This would allow infrastructure tools like [kube-green](https://kube-green.dev/) or cron jobs to explicitly put Ollama to sleep during off-hours, without having to aggressively kill the Docker container.

**Comment by nebula-it** [comment]
@mgifford If you are collecting metrics from GPU and have alert manager setup, you can use this manifest to deploy a container that looks for GPU power usage alert and suspends/resume based off that. I've had this running for few months and its been working flawlessly, hope it helps others here.

<details><summary>manifest.yaml</summary>
<p>

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-fix
data:
  gpu-fix: |
    # Runs continuously and checks Alertmanager every 5 minutes

    $alertmanagerUrl = "http://vmalertmanager-vm-stack.victoria-metrics.svc.cluster.local:9093"

    # Custom timezone for logs only
    $logTimeZone = [System.TimeZoneInfo]::FindSystemTimeZoneById("America/Los_Angeles")

    function Get-LogTime {
        return [System.TimeZoneInfo]::ConvertTimeFromUtc(
            (Get-Date).ToUniversalTime(),
            $logTimeZone
        ).ToString("yyyy-MM-dd hh:mm:ss tt")
    }

    $filters = @(
        'alertname="GPUPowerUsageWarning"'
    )

    $query = ($filters | ForEach-Object {
        "filter=$([System.Web.HttpUtility]::UrlEncode($_))"
    }) -join "&"

    $url  = "$alertmanagerUrl/api/v2/alerts?active=true&$query"

    # Prevent repeated suspend/resume actions for the same firing instance
    $alreadyHandled = $false

    while ($true) {

        try {

            $alerts = Invoke-RestMethod -Uri $url -Method Get

            if ($alerts.Count -eq 0) {
                Write-Host "$(Get-LogTime) Alert not firing"

                # Reset state when alert clears
                $alreadyHandled = $false
            }
            else {

                $firingLongEnough = $false

                foreach ($alert in $alerts) {

                    # Keep alert timestamps in UTC
                    $startsAt = [DateTime]::Parse($alert.startsAt).ToUniversalTime()
                    $now = (Get-Date).ToUniversalTime()

                    $duration = $now - $startsAt

                    Write-Host "$(Get-LogTime) Alert firing for $([math]::Round($duration.TotalMinutes,2)) minutes"

                    if ($duration.TotalMinutes -ge 5) {
                        $firingLongEnough = $true
                        break
                    }
                }

                if ($firingLongEnough -and -not $alreadyHandled) {

                    Write-Host "$(Get-LogTime) Suspending NVIDIA GPU"
                    "suspend" | Set-Content -Path "/proc/driver/nvidia/suspend"
                    Start-Sleep -Seconds 2
                    Write-Host "$(Get-LogTime) Resuming NVIDIA GPU"
                    "resume" | Set-Content -Path "/proc/driver/nvidia/suspend"
                    $alreadyHandled = $true
                }
                elseif (-not $firingLongEnough) {
                    Write-Host "$(Get-LogTime) Alert has not been firing for 5 minutes yet"
                }
                else {
                    Write-Host "$(Get-LogTime) Alert already handled"
                }
            }
        }
        catch {
            Write-Error "$(Get-LogTime) Failed to query Alertmanager: $_"
        }

        # Wait 5 minutes before checking again
        Start-Sleep -Seconds 300
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-fix
  labels:
    app.kubernetes.io/name: gpu-fix
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: gpu-fix
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gpu-fix
    spec:
      enableServiceLinks: false
      runtimeClassName: nvidia
      containers:
        - name: gpu-fix
          securityContext:
            capabilities:
              add:
              - SYS_ADMIN
          env:
            - name: POWERSHELL_TELEMETRY_OPTOUT
              value: "1"
            - name: POWERSHELL_UPDATECHECK
              value: "Off"
          command:
            - pwsh
            - /mnt/gpu-fix.ps1
          image: "spokhrel/powershell:alpine-pwsh@sha256:83195dfdce325c8340c94c776f74211e683c4efadce48ea8e5f99e0888eae0ee"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              nvidia.com/gpu: "1"
            requests:
              cpu: 50m
              memory: 10Mi
          volumeMounts:
            - name: config
              mountPath: /mnt/
      volumes:
        - name: config
          configMap:
            items:
            - key: gpu-fix
              path: gpu-fix.ps1
            name: gpu-fix
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: gpu-fix
  labels:
    app.kubernetes.io/name: gpu-fix
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: gpu-fix
  egress:
    - toEndpoints:
      - matchLabels:
          io.cilium.k8s.policy.serviceaccount: vmalertmanager-vm-stack
          io.kubernetes.pod.namespace: victoria-metrics
      toPorts:
      - ports:
        - port: "9093"
          protocol: TCP

---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: lab-infra
spec:
  groups:
  - name: gpu
    params: {}
    rules:
    - alert: GPUPowerUsageWarning
      annotations:
        description: GPU power usage is over 10W for past 10 minuters. Current Power Usage is  {{`{{ $value }}`}}W.
        summary: GPU Power Usage at {{`{{ $value }}`}}W
      expr: |-
        avg_over_time(sum(DCGM_FI_DEV_POWER_USAGE{}) by (gpu)[10m]) > 10 < 20
      for: 10m
      labels:
        severity: warning
```


</p>
</details>
