### ISSUE TITLE
Ollama stops accessing GPU and Reverts to CPU after runing for extended periods

### ISSUE THREAD

**Issue by loca5790** [ollama/ollama#8594]
### What is the issue?

I have ollama set to be persistent in my VRAM based off my homeassistant usage.  I moved to an RTX3090 and after sometimes 12 hours and other times a day plus Ollama will stop using the GPU and revert to CPU only.  It then gets stuck spooling the CPU up for hours at a time without generating any response.

System is:
Ryzen 5700G
64GB Ram
RTX3090

Ollama is running via a docker compose:
```
services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: if_not_present
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    ports:
      - ${OLLAMA_WEBAPI_PORT-11434}:11434
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu, compute, utility] #["gpu"]
            count: all
    environment:
      - OLLAMA_DEBUG=1
      - CUDA_VISIBLE_DEVICES=0  # Force use of the GPU

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped


volumes:
  ollama: {}
  open-webui: {}
```

I tried adding the CUDA_VISIBLE_DEVICES to force use of GPU.

A restart of the container will bring it back up and load it back into GPU.  I have tried to stress test it by running multiple parallel conversation agents without any issues dropping the GPU.

There are no instances in the log that I can find where the GPU becomes unavailable or anything in debug.   The only thing that alerts me in the log it has dropped the GPU is that on a request it will load the model and reference CPU.

It could be a me thing, but spent a few days now without luck.  I've had this happen on two machines now.

Second machine this happened on:
Same docker compose setup running in a VM on ubuntu server.
RTX3060 running llava-phi3 as the model and not persistent only as requested

### OS

Docker, Linux

### GPU

Nvidia

### CPU

Intel, AMD

### Ollama version

0.5.4
