### ISSUE TITLE
ollama docker api how to bind 0.0.0.0?

### ISSUE THREAD

**Issue by CoderCore** [ollama/ollama#8881]
i use a ollama docker, api bind localhost:11434 default, how to change it?

**Comment by rick-github** [comment]
```console
docker run -p 11434:11434 ollama/ollama
```
or
```yaml
services:
  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
```
