### ISSUE TITLE
Ollama Does Not Utilize Multiple Instances of the Same Model for Parallel Processing

### ISSUE THREAD

**Issue by BennisonDevadoss** [ollama/ollama#9054]
I have a server with two Nvidia L4 GPUs, and I’m running the LLaMA 3.1 8B model using Ollama. Here’s the current behavior:  

1. **What Works:**  
   - If a model is large enough to require both GPUs, Ollama successfully splits the workload and utilizes both GPUs for the same instance.  
   - If different models are loaded, Ollama utilizes the available VRAM efficiently and runs them concurrently across the GPUs.  

2. **What Does Not Work:**  
   - When multiple users send concurrent requests, Ollama doesn’t load multiple instances of the same model on available VRAM to handle parallel requests. I’ve set the `OLLAMA_NUM_PARALLEL` parameter to 3, but it doesn’t seem to have any effect.  

**What I Want to Achieve:**  
- I’d like Ollama to load multiple instances of the same model on different GPUs or available VRAM to handle parallel user requests efficiently.  

**Questions:**  
- Why doesn’t Ollama load multiple instances of the same model for parallel processing?  
- Is there any configuration or workaround to achieve this behavior?  

Any help or insights would be greatly appreciated!

**Comment by rick-github** [comment]
ollama doesn't load a model multiple times, what `OLLAMA_NUM_PARALLEL` does is create a context buffer for each parallel request.  The model weights are the same for each context buffer.  The clients send 3 simultaneous requests and they get processed concurrently.  If more simultaneous requests than completion slots are sent, they are queued up until one of the on-going completions is finished.  See [here](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-does-ollama-handle-concurrent-requests) for more info on concurrent request processing.

**Comment by pdevine** [comment]
@BennisonDevadoss as @rick-github mentioned, you don't need to waste the VRAM loading the same model into memory multiple times. I'm going to go ahead and close the issue as answered, but feel free to keep commenting.

**Comment by BilibalaX** [comment]
I have a similar question. With four GPUs (40GB VRAM), the model size (20GB) is ok to load on each GPU. My task is to input 100,000 messages for information extraction. If I set OLLAMA_NUM_PARALLEL as 4, does it mean I have tasks running on each of the GPUs separately and I can have 4 times the speed?

Then the other parameter OLLAMA_MAX_LOADED_MODELS is the maximum number of models that can be loaded. If I set it as 4, will Ollama regard them as 4 instances?

**Comment by rick-github** [comment]
No, if you set `OLLAMA_NUM_PARALLEL=4`, ollama will process up to 4 requests at a time but which GPU they run on is indeterministic.  If you really must have each GPU processing a different request simultaneously, you need to run 4 ollama servers, assign each a different GPU with `CUDA_VISIBLE_DEVICES`, and use a load balancing proxy in front the distribute the queries.  

Note ollama gets better utilization when a single GPU does concurrent requests:

![Image](https://github.com/user-attachments/assets/1c6c3b30-93ea-46c7-95fc-681d83776267)

So you could also set `OLLAMA_NUM_PARALLEL` for each of these servers and increase throughput.  For example:

```yaml
x-ollama: &ollama
  image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
  volumes:
    - ${OLLAMA_MODELS-./ollama}:/root/.ollama
  environment: &env
    OLLAMA_KEEP_ALIVE: ${OLLAMA_KEEP_ALIVE--1}
    OLLAMA_LOAD_TIMEOUT: ${OLLAMA_LOAD_TIMEOUT-5m}
    OLLAMA_MAX_LOADED_MODELS: 1
    OLLAMA_NUM_PARALLEL: 2
    OLLAMA_FLASH_ATTENTION: ${OLLAMA_FLASH_ATTENTION-0}
    OLLAMA_DEBUG: ${OLLAMA_DEBUG-1}
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

services:
  ollama-1:
    << : *ollama
    environment:
      << : *env
      CUDA_VISIBLE_DEVICES: 0

  ollama-2:
    << : *ollama
    environment:
      << : *env
      CUDA_VISIBLE_DEVICES: 1

  ollama-3:
    << : *ollama
    environment:
      << : *env
      CUDA_VISIBLE_DEVICES: 2

  ollama-4:
    << : *ollama
    environment:
      << : *env
      CUDA_VISIBLE_DEVICES: 3

  ollama:
    image: nginx-lb
    build:
      dockerfile_inline: |
        FROM nginx:latest
        RUN cat > /etc/nginx/conf.d/default.conf <<EOF
        upstream ollama_group {
          least_conn;
          server ollama-1:11434 max_conns=2;
          server ollama-2:11434 max_conns=2;
          server ollama-3:11434 max_conns=2;
          server ollama-4:11434 max_conns=2;
        }
        server {
          listen 11434;
          server_name localhost;
          location / {
            proxy_pass http://ollama_group;
          }
        }
        EOF
    ports:
      - 11434:11434
```
