### ISSUE TITLE
APIkey

### ISSUE THREAD

**Issue by gsm1258** [ollama/ollama#9114]
Currently, there are many scanning tools on the internet that perform port scans. For security reasons, please add an API key setting.

**Comment by FelisDwan** [comment]
I also require this feature. My ollama api has been discovered and used (even I've changed ollama port), so I can only turn off ollama temporarily and turn it on when I need to use it.

**Comment by Hashem-Qaryouti** [comment]
Hello, I would like to work on adding this feature, could you assign me?

**Comment by gsm1258** [comment]
> Hello, I would like to work on adding this feature, could you assign me?

If the next version of Ollama updates to include an API key feature, please ensure that Open-WebUI also adds a corresponding setting option to input the Ollama API key.

**Comment by Hashem-Qaryouti** [comment]
I got it. Could you officially assign me?

**Comment by Hashem-Qaryouti** [comment]
Hey, is this feature something the maintainers would like to add? I’d be happy to work on it if approved.

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/1053#issuecomment-2558705136

**Comment by lemassykoi** [comment]
don't expose your instances to WAN, use a VPN, and if you can't, restrict the source IP

PiVPN can help you

**Comment by jejbq** [comment]
It's sad that `OLLAMA_API_KEY` is only implemented for [Ollama public service](https://docs.ollama.com/api/authentication) (misleading if you ask any AI if you can create an API_KEY for Ollama) and not `ollama serve`; Ollama on-premises deserve better protection for [Critical Flaws in Ollama AI Framework Could Enable DoS, Model Theft, and Poisoning](https://thehackernews.com/2024/11/critical-flaws-in-ollama-ai-framework.html).

My workaround in Docker Stack (RFC) allow /v1 only when authenticated (/api is too dangerous and maybe need another privileged key `OLLAMA_ADMIN_API_KEY`):

``` yaml
# ENV:
# OLLAMA_SERVER_NAME=ollama.company
# OLLAMA_API_KEY=b33fb33f-b33f-b33f-b33f-b33fb33fb33f
# OLLAMA_ACL=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16

  # curl -sL -w "\nHTTP Code: %{http_code}\n" https://ollama.company/api/tags # 451
  # curl -sL -w "\nHTTP Code: %{http_code}\n" -H "Authorization: Bearer bad-key" https://ollama.company/v1/models # 401
  # curl -sL -w "\nHTTP Code: %{http_code}\n" -H "Authorization: Bearer ${OLLAMA_API_KEY}" https://ollama.company/v2/models # 451
  # curl -sL -H "Authorization: Bearer ${OLLAMA_API_KEY}" https://ollama.company/v1/models | jq -r '.data[].id' # 200
  caddy:
    image: caddy:2.11
    hostname: caddy
    environment:
      OLLAMA_API_KEY: '${OLLAMA_API_KEY}'
    entrypoint: ["/bin/sh", "-xc"]
    command:
      - |
        printf '%s\n' \
          ':80 {' \
          '  @not_v1 not path /v1/*' \
          '  respond @not_v1 "Unavailable For Legal Reasons" 451' \
          '' \
          '  @unauth not header Authorization "Bearer {env.OLLAMA_API_KEY}"' \
          '  respond @unauth "Unauthorized" 401' \
          '' \
          '  reverse_proxy http://ollama:11434 {' \
          '    header_up -Authorization' \
          '    flush_interval -1' \
          '  }' \
          '}' \
          > /tmp/Caddyfile
        caddy run --config /tmp/Caddyfile --adapter caddyfile
    depends_on:
      - ollama
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: 'true'
        traefik.http.routers.caddy.rule: 'Host(`${OLLAMA_SERVER_NAME}`)'
        traefik.http.routers.caddy.entrypoints: 'websecure'
        traefik.http.routers.caddy.tls: 'true'
        traefik.http.routers.caddy.tls.certresolver: 'letsencrypt'
        traefik.http.middlewares.caddy-acl.ipallowlist.sourceRange: '${OLLAMA_ACL}'
        traefik.http.routers.caddy.middlewares: 'caddy-acl, default-https@file'
        traefik.http.services.caddy.loadbalancer.server.port: '80'
```
