### ISSUE TITLE
How to Enable Flash Attention in Ollama Docker Deployment?

### ISSUE THREAD

**Issue by lixiangge** [ollama/ollama#9327]
I’m trying to deploy Ollama using Docker, and I want to enable Flash Attention for performance improvements. However, I’m not sure where to set the environment variable to activate it. Could anyone point me to the proper place or method to configure it?

**Comment by rick-github** [comment]
```yaml
services:
  ollama:
    environment:
     OLLAMA_FLASH_ATTENTION: 1
```
or
```
docker run -e OLLAMA_FLASH_ATTENTION=1 ollama/ollama
```
