### ISSUE TITLE
TLS --insecure

### ISSUE THREAD

**Issue by 3GDXC** [ollama/ollama#9391]
### What is the issue?

When running ollama as a docker container where the host is using a proxy like zscaler; ollama run [model] fails due to failure to validate certificate.

Please consider either allowing the user to over this check and accept the insecure connection;  or provide a environment variable/switch or configuration option to install a certificate authority certificate.

### Relevant log output

```shell

```

**Comment by flywiththetide** [comment]
It looks like your issue is related to **TLS certificate validation** when running Ollama behind a **proxy like Zscaler**. Here are two possible solutions:

### **Option 1: Disable TLS Verification (Not Recommended for Production)**
You can disable TLS certificate verification by setting the following environment variable when running the container:

```bash
docker run -e NODE_TLS_REJECT_UNAUTHORIZED=0 ollama/ollama
```
Alternatively, if using **cURL inside the container**, add:
```bash
curl -k https://registry.ollama.ai
```
This will bypass TLS validation but is **not secure** for production use.

---

### **Option 2: Install Your Proxy’s Root CA Certificate**
A more secure approach is to **install your Zscaler (or proxy) CA certificate** inside the container.

1. **Copy the Zscaler Root CA certificate into the container**:
   ```bash
   docker cp zscaler.crt <container-id>:/usr/local/share/ca-certificates/
   ```
   
2. **Update the certificate store**:
   ```bash
   docker exec -it <container-id> update-ca-certificates
   ```

3. **Restart the container**:
   ```bash
   docker restart <container-id>
   ```

After doing this, Ollama should trust your proxy’s certificate and allow downloads.

Let me know if you need help finding the **correct CA certificate** for your proxy!

**Comment by rick-github** [comment]
Another couple of ways to handle this.

You can mount the cert in the container and then modify the entrypoint to update the certificates on every start of the container:
```yaml
services:
  ollama:
    image ollama/ollama:latest
    volumes:
      - ollama-data:/root/.ollama
      - ./zscalert.crt:/usr/local/share/ca-certificates/zscaler.crt
    entrypoint: bash -c 'update-ca-certificates ; exec ollama serve'
```
Or you can inherit from the ollama container and roll your own image:
```dockerfile
FROM ollama/ollama:latest

COPY zscaler.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates
```
```
docker build -f Dockerfile -t ollama-cert .
```
```yaml
services:
  ollama-cert:
    image: ollama-cert
    volumes:
      - ollama-data:/root/.ollama
```
