### ISSUE TITLE
Configuring Ollama to Use a Custom Model Registry

### ISSUE THREAD

**Issue by sgadheth31** [ollama/ollama#9409]
change Ollama's model library from the default registry.ollama.ai to a custom URL (such as your own private model registry)
Containerresistery-na.myorganization.net/container-release/myproject/<all model gguf file >

When i am firing 

Ollama create llama3 it pull model form my organization repo instead of registry.ollama.ai. I am tuning in kubernetes  how to force to used my custom url instead of registry.ollama.ai

**Comment by flywiththetide** [comment]
You can configure Ollama to pull models from a **custom model registry** instead of the default `registry.ollama.ai` by modifying your setup.

### **Option 1: Set the OLLAMA_REGISTRY_URL**
If Ollama supports a **custom registry environment variable**, try setting:

```bash
export OLLAMA_REGISTRY_URL="https://containerregistry-na.myorganization.net/container-release/myproject/"
```

Restart Ollama after applying this setting.

### **Option 2: Modify the Ollama Container in Kubernetes**
If running Ollama in **Kubernetes**, update your deployment YAML:

```yaml
containers:
  - name: ollama
    image: your-ollama-image
    env:
      - name: OLLAMA_REGISTRY_URL
        value: "https://containerregistry-na.myorganization.net/container-release/myproject/"
```
Apply the change:
```bash
kubectl apply -f your-deployment.yaml
```

### **Option 3: Manually Pull Models**
If the registry URL cannot be changed directly, you can **manually pull and store models**:

```bash
docker pull containerregistry-na.myorganization.net/container-release/myproject/ollama-model:latest
docker tag containerregistry-na.myorganization.net/container-release/myproject/ollama-model:latest ollama-model:latest
```

Let me know if this works or if your registry requires **authentication settings**!
