### ISSUE TITLE
Ollama logic for GPU choice is suboptimal.

### ISSUE THREAD

**Issue by CoolShades** [ollama/ollama#9462]
### What is the issue?

# Suboptimal GPU Selection Logic in Ollama

## Issue Description
Ollama's current GPU selection logic doesn't optimally allocate models based on GPU performance characteristics. When multiple GPUs with different performance profiles are present, Ollama should prioritize the fastest GPU for small models and utilize multiple GPUs for larger models that exceed the memory of a single GPU.

## Current Behavior
- With multiple GPUs present, Ollama appears to make GPU selection decisions based primarily on VRAM capacity rather than performance characteristics
- In a mixed GPU environment (e.g., RTX 4090 + RTX 3090), Ollama may use the slower GPU with slightly more VRAM instead of the faster GPU
- When a model exceeds the memory of the faster GPU, Ollama may fall back to system RAM rather than utilizing both GPUs

## Expected Behavior
Ollama should:
1. Default to using the fastest GPU for models that fit within its VRAM
2. Utilize multiple GPUs for models that exceed the memory of the fastest GPU
3. Never use only the slower GPU when a faster GPU is available
4. Provide configurable options to specify preferred GPU selection logic

## System Configuration
```
Environment:
- RTX 4090 (24564 MiB VRAM, Device #0) - Faster but slightly less VRAM
- RTX 3090 (24576 MiB VRAM, Device #1) - Slower but marginally more VRAM
- Docker configuration with nvidia-runtime
```

## Docker Compose Configuration
```yaml
ollama:
  image: ollama/ollama
  environment:
    - NVIDIA_VISIBLE_DEVICES=0,1
    - CUDA_DEVICE_ORDER=PCI_BUS_ID
    - OLLAMA_NUM_GPU=2
    - OLLAMA_HOST=0.0.0.0
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
```

## Proposed Solutions
1. Add configuration options to specify GPU selection preferences:
   - `OLLAMA_PREFERRED_GPU`: Specify primary GPU device index
   - `OLLAMA_GPU_STRATEGY`: Options like "fastest-first", "memory-first", or "performance-model"

2. Implement smarter default behavior that considers both VRAM capacity and GPU performance metrics when making allocation decisions

3. Add a way to specify model-specific GPU configurations without needing custom entrypoint scripts

## Impact
This issue affects users with heterogeneous GPU setups who want to maximize performance. The current behavior leads to suboptimal performance by not utilizing the fastest available GPU or by falling back to system RAM instead of using multiple GPUs.

## Workarounds
Currently using custom entrypoint scripts or manually setting `CUDA_VISIBLE_DEVICES` for different models, but this is cumbersome and requires manual intervention.

### Relevant log output

```shell

```

### OS

Docker

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.5.12
