### ISSUE TITLE
add password

### ISSUE THREAD

**Issue by dzy888** [ollama/ollama#9488]
I think it's safer to need a password that way

**Comment by rick-github** [comment]
https://github.com/ollama/ollama/issues/9114

**Comment by ice6** [comment]
@rick-github maybe a `nginx` or `caddy` configuration example for such issue will make such issue disappear.

**Comment by rick-github** [comment]
Updated version showing examples of both nginx and caddy configuration.
```yaml
services:
  ollama-backend:
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    volumes:
      - ${OLLAMA_MODELS-./ollama}:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=${OLLAMA_KEEP_ALIVE--1}
      - OLLAMA_DEBUG=${OLLAMA_DEBUG-1}

  ollama-nginx:
    image: nginx-api-key
    build:
      dockerfile_inline: |
        FROM nginx:latest
        RUN mkdir -p /etc/nginx/templates && cat > /etc/nginx/templates/variables.conf.template <<"EOF"
        map $$http_authorization $$valid_key {
          default                   0;
          "Bearer $$OLLAMA_API_KEY" 1;
        }
        EOF
        RUN cat > /etc/nginx/conf.d/default.conf <<"EOF"
        server {
          listen 11434;
          location / {
            if ($$valid_key = 0) {
              return 401; # unauthorized
            }
            proxy_pass http://ollama-backend:11434;
          }
        }
        EOF
    environment:
      OLLAMA_API_KEY: ${OLLAMA_API_KEY-secretkey}
    depends_on:
      - ollama-backend
    ports:
      - 11435:11434

  ollama-caddy:
    image: caddy-api-key
    build:
      dockerfile_inline: |
        FROM caddy:latest
        RUN cat > /etc/caddy/Caddyfile <<"EOF"
        :11434
        @unauthorized expression ! header({"Authorization": "Bearer {$$OLLAMA_API_KEY}"})
        respond @unauthorized 401
        reverse_proxy ollama-backend:11434
        EOF
    environment:
      OLLAMA_API_KEY: ${OLLAMA_API_KEY-secretkey}
    depends_on:
      - ollama-backend
    ports:
      - 11436:11434
```
