### ISSUE TITLE
non global CUDA_VISIBLE_DEVICES

### ISSUE THREAD

**Issue by NGC13009** [ollama/ollama#9607]
The currently available GPU are set globally by the environment variable. Would it be possible to provide a method that would allow me to specify that I want different models to be loaded into different GPUs?

For example, having `qwen2.5:32b` load into `cuda:0,cuda:1` and having `qwq` in larger contexts load into `cuda:2~6` this way. This is because I've found that the current loading, no matter how sequential, results in multiple models being evenly distributed across multiple graphics cards, which is less efficient and wastes more video memory.

Also, setting different concurrency numbers for different models is urgently needed. like [#8842](https://github.com/ollama/ollama/issues/8842)

**Comment by rick-github** [comment]
Use multiple ollama servers, bind the required GPUs with CUDA_VISIBLE_DEVICES, run a proxy in front to provide a unified interface.

For example:
```yaml
x-ollama: &ollama
  image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
  volumes:
    - ${OLLAMA_MODELS-./ollama}:/root/.ollama
  environment: &env
    OLLAMA_KEEP_ALIVE: ${OLLAMA_KEEP_ALIVE--1}
    OLLAMA_LOAD_TIMEOUT: ${OLLAMA_LOAD_TIMEOUT-5m}
    OLLAMA_MAX_LOADED_MODELS: 1
    OLLAMA_NUM_PARALLEL: 1
    OLLAMA_FLASH_ATTENTION: ${OLLAMA_FLASH_ATTENTION-0}
    OLLAMA_DEBUG: ${OLLAMA_DEBUG-1}
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

services:
  ollama-1:
    << : *ollama
    environment:
      << : *env
      CUDA_VISIBLE_DEVICES: 0,1

  ollama-2:
    << : *ollama
    environment:
      << : *env
      CUDA_VISIBLE_DEVICES: 2,3,4,5,6

  ollama:
    image: nginx-lb
    build:
      dockerfile_inline: |
        FROM nginx:latest
        RUN cat > /etc/nginx/conf.d/default.conf <<EOF
        upstream ollama_group {
          least_conn;
          server ollama-1:11434 max_conns=8;
          server ollama-2:11434 max_conns=8;
        }
        server {
          listen 11434;
          server_name localhost;
          location / {
            proxy_pass http://ollama_group;
          }
        }
        EOF
    ports:
      - 11434:11434
```

**Comment by NGC13009** [comment]
Due to special network reasons within China, maybe not quite able to use docker solution, can you give a solution to run directly in the system environment? For example, defining temporary environment variables directly within a specific terminal, pulling up the model and bypassing ollama's own model process management. 

Also, with this approach, does nginx automatically route different models? For example, if ollama-1 runs model A and ollama-2 runs model B, any api requests are automatically routed through?

**Comment by rick-github** [comment]
The docker containers are just a useful management mechanism, you can just start individual servers:
```bash
#!/bin/bash
export OLLAMA_HOST=:11435
export CUDA_VISIBLE_DEVICES=0,1
ollama serve &
```
```bash
#!/bin/bash
export OLLAMA_HOST=:11436
export CUDA_VISIBLE_DEVICES=2,3,4,5,6
ollama serve &
```
and configure nginx to talk to the servers:
```
        upstream ollama_group {
          least_conn;
          server localhost:11435 max_conns=8;
          server localhost:11436 max_conns=8;
        }
        server {
          listen 11434;
          server_name localhost;
          location / {
            proxy_pass http://ollama_group;
          }
        }
```
For routing to particular models, you can use litellm in place of nginx and set up aliases for particular models:
```
  - model_name: qwen2.5-coder
    litellm_params:
      model: ollama/qwen2.5-coder:32b
      api_base: http://localhost:11435

  - model_name: qwq
    litellm_params:
      model: ollama/qwq
      api_base: http://localhost:11436
```
But this means switching to the OpenAI format as litellm doesn't have an ollama API compatible endpoint (or didn't, last time I checked).

There are many other ollama proxy servers on github, some might have request routing based on model.
