### ISSUE TITLE
ollama/ollama Cannot find the configuration file for ollama in the image

### ISSUE THREAD

**Issue by Tu1231** [ollama/ollama#9814]
I deployed Docker on my server and pulled the ollama/ollama image. After running the ollama/ollama container and deploying the model, I found that the maximum concurrent request count for calling the model was 3. I wanted to set this request count higher in ollama, but I couldn't find the relevant configuration files. When I checked~/. ollama in the container, I only found the history id_ ed25519 id_ ed25519. pub models, and I couldn't find any configuration files related to ollama. I checked the relevant documentation, but I couldn't find any configuration files related to ollama

**Comment by rick-github** [comment]
Set configuration environment variables.
```yaml
services:
  ollama:
    image: ollama/ollama:latest
    environment:
      - OLLAMA_NUM_PARALLEL=5
      - OLLAMA_CONTEXT_LENGTH=5678
```
